OPTIONS OBS = MAX
		REUSE = YES
		COMPRESS = YES
		VALIDVARNAME= ANY;
LIBNAME OIT "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/OIT";
LIBNAME FAT_SUM "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/OIT/FAT_SUM";
LIBNAME PLANTA "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/PLNT/FIXO_BL_TV";

%MACRO IMPORT_NBA;

%LET MES=202101;
%LET NMES=202012;

DATA WORK.CHAMADAS_&MES._TITULAR_OIT_FB;

LENGTH

ANOMES    8
CPF_FLAG    $20
UCID    8
ID_BUNDLE    $10
VAL_ID_BUNDLE    $8
NUM_CPF_CNPJ    8
NUM_CPF_DIGITADO_CHAMADA    $20
NUM_CPF_INFORMADO    $20
ID_CPF_FICTICIO    $20
DDD_TELEFONE    8
ID_TERMINAL    $20
TP_PRODUTO_OITOTAL    $20
BUNDLE_FINAL    $20
CELULA_OPERADOR    $10
NOME_GRUPO_OPERADOR    $30
ID_OPERADOR    $10
NOME_OPERADOR    $50
LOGIN_AGENTE_CHAMADA    $10
DT_LIGACAO    8
HORARIO_LIGACAO 8
DT_CRIACAO    $20
COD_UF    $10
NOME_CLIENTE    $50
ID_REGISTRO_CHAMADA    8
TP_CHAMADA    $20
COD_REGIAO    $10
CLUSTER_CLIENTE    $99
NUM_GRUPO_CLUSTER    8
MAX_VELOC_VELOX_DISPONIVEL    8
MAX_VELOC_VELOX_CONSULTADA    8
TEMPO_VIG_CONTR_FIDEL_OITOTAL    8
TEMPO_VIG_CONTR_FIDEL_TV    8
TEMPO_VIG_CONTR_FIDEL_MV    8
QTD_DIAS_ATRASO_PAG_OIT    8
QTD_DIAS_ATRASO_PAG_TV    8
QTD_DIAS_ATRASO_PAG_MV    8
MOTIVO_LIGACAO_CATEGORIA    $50
MOTIVO_LIGACAO_NOME    $50
NUM_CONTRATO_TV_ASSOCIADO    8
TP_CONTRATO_TV    $20
NUM_TERMINAL_MV_ASSOCIADO    $20
SEM_OFERTA_1    $20
SEM_OFERTA_2    $20
RESULTADO_DA_CHAMADA    $20
RESULTADO    $20
DETALHE_MIGDOWN_CANCEL    $50
PRODUTOS_MANTIDOS_ALONE    $20
PRODUTOS_CANCELADOS    $20
DETALHE_RESULTADO_DA_CHAMADA    $60
STATUS_FINAL_FIXO    $40
STATUS_FINAL_BANDA_LARGA    $40
STATUS_FINAL_TV    $40
STATUS_FINAL_MOVEL_TITULAR    $40
DETALHE_STATUS_FINAL_FIXO    $40
DETALHE_STATUS_FINAL_BL    $40
DETALHE_STATUS_FINAL_TV    $40
DETALHE_STATUS_FINAL_MV    $40
DETALHE_CHAMADA_IMPRODUTIVA    $20
RESULTADO_ATENDIMENTO_N28    $30
NUM_PRIMEIRO_CONTATO    8
NUM_SEGUNDO_CONTATO    $20
POSSE_DACC    $10
NOVO_DACC    $10
POSSE_CONTA_ONLINE    8
NOVO_CONTA_ONLINE    $10
EMAIL_ENVIO    $40
NOME_OFERTA_ACEITA    $70
NIVEL_PRECO_OFERTA_ACEITA    $10
IND_FIDELIDADE_OFERTA    8
CATEGORIA_OFERTA    $30
CATEGORIA_RV_OFERTA    8
STATUS_ULTIMA_OFERTA    $10
ARPU_OITOTAL_ANTES    8
ARPU_OITOTAL_DEPOIS    8
ARPU_TARGET    8
ARPU_LIGACAO    8
ARPU_RECEITA_ANTES    8
ARPU_RECEITA_DEPOIS    8
ARPU_FIXO_ANTES    8
ARPU_FIXO_DEPOIS    8
ARPU_RECARGA_ANTES    8
ARPU_RECARGA_DEPOIS    8
ARPU_VELOX_ANTES    8
ARPU_VELOX_DEPOIS    8
ARPU_TV_ANTES    8
ARPU_TV_DEPOIS    8
ARPU_MV_ANTES    8
ARPU_MV_DEPOIS    8
PACOTE_FIXO_ANTES    $30
PACOTE_FIXO_DEPOIS    $30
NOME_PAC_FIXO_ANTES    $30
NOME_PAC_FIXO_DEPOIS    $30
NOME_PAC_FIXO_LD_ANTES    $10
NOME_PAC_FIXO_LD_DEPOIS    $10
NOME_PAC_FIXO_VC_ANTES    $10
NOME_PAC_FIXO_VC_DEPOIS    $10
NOME_PAC_FIXO_SD_ANTES    $20
NOME_PAC_FIXO_SD_DEPOIS    $20
QTE_RECARGA_AUTO_01    8
QTE_RECARGA_AUTO_10    8
QTE_RECARGA_AUTO_15    8
QTE_RECARGA_AUTO_20    8
QTE_RECARGA_AUTO_01_DEPOIS    8
QTE_RECARGA_AUTO_10_DEPOIS    8
QTE_RECARGA_AUTO_15_DEPOIS    8
QTE_RECARGA_AUTO_20_DEPOIS    8
VAL_ASS_FIXO_ANTES    8
VAL_ASS_FIXO_DEPOIS    8
VAL_ASS_FIXO_SD_ANTES    8
VAL_ASS_FIXO_SD_DEPOIS    8
VAL_ASS_FIXO_LD_ANTES    8
VAL_ASS_FIXO_LD_DEPOIS    8
VAL_ASS_FIXO_VC_ANTES    8
VAL_ASS_FIXO_VC_DEPOIS    8
VAL_EXC_FIXO_LOC_FF_ANTES    8
VAL_EXC_FIXO_LOC_FM_ANTES    8
VAL_EXC_FIXO_LOC_FMOUT_ANTES    8
VAL_EXC_FIXO_LD_31_ANTES    8
VAL_RECARGA_PRI_TOP_OF    8
VAL_RECARGA_PRI_TOP_OF_SEG_EST    8
VAL_RECARGA_PRI_TOP_OF_TER_EST    8
VAL_RECARGA_SEGUNDA_TOP_OFERTA    8
VAL_RECARGA_SEG_TOP_OF_SEG_EST    8
VAL_RECARGA_SEG_TOP_OF_TER_EST    8
VAL_RECARGA_TER_TOP_OF    8
VAL_RECARGA_TER_TOP_OF_SEG_EST    8
VAL_RECARGA_TER_TOP_OF_TER_EST    8
VAL_FIXO_PRIMEIRA_TOP_OFERTA    8
VAL_FIXO_PRI_TOP_OF_SEG_EST    8
VAL_FIXO_PRI_TOP_OF_TER_EST    8
VAL_FIXO_SEGUNDA_TOP_OFERTA    8
VAL_FIXO_SEG_TOP_OF_SEG_EST    8
VAL_FIXO_SEG_TOP_OF_TER_EST    8
VAL_FIXO_TERCEIRA_TOP_OFERTA    8
VAL_FIXO_TER_TOP_OF_SEG_EST    8
VAL_FIXO_TER_TOP_OF_TER_EST    8
VAL_TAD_FIXO    8
NOME_PAC_VELOX_ANTES    $10
NOME_PAC_VELOX_DEPOIS    $10
NOME_PAC_BLM_ANTES    $10
NOME_PAC_BLM_DEPOIS    $10
VELOC_VELOX_OFERTA_ACEITA    $40
VAL_VELOX_PRIMEIRA_TOP_OFERTA    8
VAL_VELOX_PRI_TOP_OF_SEG_EST    8
VAL_VELOX_PRI_TOP_OF_TER_EST    8
VAL_VELOX_SEGUNDA_TOP_OFERTA    8
VAL_VELOX_SEG_TOP_OF_SEG_EST    8
VAL_VELOX_SEG_TOP_OF_TER_EST    8
VAL_VELOX_TERCEIRA_TOP_OFERTA    8
VAL_VELOX_TER_TOP_OF_SEG_EST    8
VAL_VELOX_TER_TOP_OF_TER_EST    8
VAL_THAB_VELOX    8
IND_POSSE_COMBATE    8
IND_POSSE_ETNICO    8
IND_POSSE_PFC    8
IND_POSSE_PLAYBOY    8
IND_POSSE_PLAYBOY_SEXYHOT    8
IND_POSSE_PRIVE    8
IND_POSSE_SEXYHOT    8
IND_POSSE_COMBATE_DEPOIS    8
IND_POSSE_ETNICO_DEPOIS    8
IND_POSSE_PFC_DEPOIS    8
IND_POSSE_PLAYBOY_DEPOIS    8
IND_POSSE_PRIVE_DEPOIS    8
IND_POSSE_SEXYHOT_DEPOIS    8
IND_POSSE_BBB_DEPOIS    8
IND_POSSE_PLAYBOYSEXHOT_DEPOIS    8
IND_POSSE_CONTEUDOON_ANTES    8
IND_POSSE_CONTEUDOON_DEPOIS    $10
IND_POSSE_DVR_ANTES    8
IND_POSSE_DVR_DEPOIS    8
IND_POSSE_PENVR_ANTES    8
IND_POSSE_PENVR_DEPOIS    8
QTD_PONTOS_ADIC_TV_ANTES    8
QTD_PONTOS_ADIC_TV_DEPOIS    8
TP_SATELITE_ANTES    $10
TP_SATELITE_DEPOIS    $10
NOME_PAC_TV_ANTES    $30
NOME_PAC_TV_DEPOIS    $30
NOME_DEGUSTACAO_TV_DEPOIS    $20
PERIODO_DEGUSTACAO_TV_DEPOIS    8
VAL_PLANO_TV_ANTES    8
VAL_PLANO_TV_DEPOIS    8
VAL_LA_CARTE_ANTES    8
VAL_LA_CARTE_DEPOIS    8
VAL_PONTOS_ADIC_ANTES    8
VAL_PONTOS_ADIC_DEPOIS    8
VAL_PENVR_ANTES    8
VAL_PENVR_DEPOIS    8
VAL_TV_PRIMEIRA_TOP_OFERTA    8
VAL_TV_PRI_TOP_OF_SEG_EST    8
VAL_TV_PRI_TOP_OF_TER_EST    8
VAL_TV_SEGUNDA_TOP_OFERTA    8
VAL_TV_SEG_TOP_OF_SEG_EST    8
VAL_TV_SEG_TOP_OF_TER_EST    8
VAL_TV_TERCEIRA_TOP_OFERTA    8
VAL_TV_TER_TOP_OF_SEG_EST    8
VAL_TV_TER_TOP_OF_TER_EST    8
VAL_THAB_TV    8
NOME_PAC_MV_VOZ_ANTES    $50
NOME_PAC_MV_VOZ_DEPOIS    $50
NOME_PAC_MV_DADOS_TIT_ANTES    $10
NOME_PAC_MV_DADOS_TIT_DEPOIS    $10
NOME_PAC_MV_LD_ANTES    $20
NOME_PAC_MV_LD_DEPOIS    $20
VAL_ASS_MV_VOZ_ANTES    8
VAL_ASS_MV_VOZ_DEPOIS    8
VAL_ASS_MV_DADOS_TIT_ANTES    8
VAL_ASS_MV_DADOS_TIT_DEPOIS    8
VAL_ASS_MV_LD_ANTES    8
VAL_ASS_MV_LD_DEPOIS    8
VAL_ASS_MV_DADOS_DEP_ANTES    8
VAL_ASS_MV_DADOS_DEP_DEPOIS    8
VAL_ASS_MV_DEP_ANTES    8
VAL_ASS_MV_DEP_DEPOIS    8
VAL_EXC_LD_ON_MV_OI_ANTES    8
VAL_EXC_LD_OFF_MV_OI_ANTES    8
VAL_EXC_LD_ON_MV_OUT_ANTES    8
VAL_EXC_LD_OFF_MV_OUT_ANTES    8
VAL_EXC_LOCAL_ON_MV_ANTES    8
VAL_EXC_LOCAL_OFF_MV_ANTES    8
VAL_EXC_SMS_MV_ANTES    8
VAL_EXC_DADOS_MV_ANTES    8
VAL_EXC_OUTROS_MV_ANTES    8
VAL_VOZ_PRIMEIRA_TOP_OFERTA    8
VAL_VOZ_PRI_TOP_OF_SEG_EST    8
VAL_VOZ_PRI_TOP_OF_TER_EST    8
VAL_DADOS_PRIMEIRA_TOP_OFERTA    8
VAL_DADOS_PRI_TOP_OF_SEG_EST    8
VAL_DADOS_PRI_TOP_OF_TER_EST    8
VAL_MOVEL_PRIMEIRA_TOP_OFERTA    8
VAL_MOVEL_PRI_TOP_OF_SEG_EST    8
VAL_MOVEL_PRI_TOP_OF_TER_EST    8
VAL_VOZ_SEGUNDA_TOP_OFERTA    8
VAL_VOZ_SEG_TOP_OF_SEG_EST    8
VAL_VOZ_SEG_TOP_OF_TER_EST    8
VAL_DADOS_SEGUNDA_TOP_OFERTA    8
VAL_DADOS_SEG_TOP_OF_SEG_EST    8
VAL_DADOS_SEG_TOP_OF_TER_EST    8
VAL_MOVEL_SEGUNDA_TOP_OFERTA    8
VAL_MOVEL_SEG_TOP_OF_SEG_EST    8
VAL_MOVEL_SEG_TOP_OF_TER_EST    8
VAL_VOZ_TERCEIRA_TOP_OFERTA    8
VAL_VOZ_TER_TOP_OF_SEG_EST    8
VAL_VOZ_TER_TOP_OF_TER_EST    8
VAL_DADOS_TERCEIRA_TOP_OFERTA    8
VAL_DADOS_TER_TOP_OF_SEG_EST    8
VAL_DADOS_TER_TOP_OF_TER_EST    8
VAL_MOVEL_TERCEIRA_TOP_OFERTA    8
VAL_MOVEL_TER_TOP_OF_SEG_EST    8
VAL_MOVEL_TER_TOP_OF_TER_EST    8
VAL_OFERTA_PRIMEIRA_TOP_OFERTA    8
VAL_OF_PRI_TOP_OF_SEG_EST    8
VAL_OF_PRI_TOP_OF_TER_EST    8
VAL_OFERTA_SEGUNDA_TOP_OFERTA    8
VAL_OF_SEG_TOP_OF_SEG_EST    8
VAL_OF_SEG_TOP_OF_TER_EST    8
VAL_OFERTA_TERCEIRA_TOP_OFERTA    8
VAL_OF_TER_TOP_OF_SEG_EST    8
VAL_OF_TER_TOP_OF_TER_EST    8
COD_PLANO_ACEITA_OITOTAL    $50
COD_CAMPANHA_ACEITA_OITOTAL    $50
COD_OFERTA_ACEITA_OITOTAL    $50
COD_CAMPANHA_ACEITA_FIXO    $60
COD_OFERTA_ACEITA_FIXO    $60
COD_CAMPANHA_ACEITA_VELOX    $50
COD_OFERTA_ACEITA_VELOX    $10
COD_CAMPANHA_ACEITA_BLM    $10
COD_OFERTA_ACEITA_BLM    $10
COD_CAMPANHA_ACEITA_TV    $40
COD_OFERTA_ACEITA_TV    $10
COD_CAMPANHA_ACEITA_VOZ_MV    $50
COD_OFERTA_ACEITA_VOZ_MV    $50
COD_CAMPANHA_ACEITA_DADOS_MV    $10
COD_OFERTA_ACEITA_DADOS_MV    $10
QTE_DEPENDENTES_ANTES    8
QTE_DEPENDENTES_DEPOIS    8
FRAN_BLM_ANTES    $10
FRAN_BLM_DEPOIS    $10
RESULTADO_ATENDIMENTO_N10    $10
RESULTADO_ATENDIMENTO_N11    $10
RESULTADO_ATENDIMENTO_N12    $10
RESULTADO_ATENDIMENTO_N13    $20
RESULTADO_ATENDIMENTO_N14    $20
RESULTADO_ATENDIMENTO_N20    8
RESULTADO_ATENDIMENTO_N21    8
RESULTADO_ATENDIMENTO_N22    $10
RESULTADO_ATENDIMENTO_N23    8
RESULTADO_ATENDIMENTO_N24    8
RESULTADO_ATENDIMENTO_N25    $10
RESULTADO_ATENDIMENTO_N26    $20
RESULTADO_ATENDIMENTO_N27    $10
RESULTADO_ATENDIMENTO_N29    $20
RESULTADO_ATENDIMENTO_N30    $20
RESULTADO_ATENDIMENTO_N31    $10
RESULTADO_ATENDIMENTO_N32    $10
RESULTADO_ATENDIMENTO_N33    $10
RESULTADO_ATENDIMENTO_N34    $10
RESULTADO_ATENDIMENTO_N35    $10
RESULTADO_ATENDIMENTO_N36    $10
RESULTADO_ATENDIMENTO_N37    $10
RESULTADO_ATENDIMENTO_N38    $10
DELTA_HIERARQUIA_VOZ_ACEITA    $10
DELTA_HIERARQUIA_DADOS_ACEITA    8
DELTA_HIERARQUIA_BL_ACEITA    8
DELTA_HIERARQUIA_TV_ACEITA    8
COD_VERSAO_MACRO    $10
COD_CLEANUP_ACEITA_BL    $10
COD_AGR_ACEITA_FIXO    $10
COD_DESCRICAO_ACEITA_FIXO    $50
COD_CAMPANHA_VOZ_TOTAL    $10
COD_CAMPANHA_PONTO_ADICIONAL    $40
COD_CAMPANHA_DEGUSTACAO    $50
COD_CAMPANHA_PACOTE_LACARTE    $30
PRI_TOP_OF_APRESENTADA    $70
PRI_TOP_OF_APRESENTADA_SEG_EST    $70
PRI_TOP_OF_APRESENTADA_TER_EST    $70
SEGUNDA_TOP_OFERTA_APRESENTADA    $70
SEG_TOP_OF_APRESENTADA_SEG_EST    $70
SEG_TOP_OF_APRESENTADA_TER_EST    $30
TER_TOP_OF_APRESENTADA    $70
TER_TOP_OF_APRESENTADA_SEG_EST    $50
TER_TOP_OF_APRESENTADA_TER_EST    $10
NOME_GUERRA_PRI_TOP_OF    $99
NOME_GUERRA_PRI_TOP_OF_SEG_EST    $99
NOME_GUERRA_PRI_TOP_OF_TER_EST    $99
NOME_GUERRA_SEGUNDA_TOP_OFERTA    $99
NOME_GUERRA_SEG_TOP_OF_SEG_EST    $99
NOME_GUERRA_SEG_TOP_OF_TER_EST    $70
NOME_GUERRA_TER_TOP_OF    $99
NOME_GUERRA_TER_TOP_OF_SEG_EST    $99
NOME_GUERRA_TER_TOP_OF_TER_EST    $10
COD_PRIMEIRA_TOP_OFERTA    $50
COD_PRI_TOP_OF_SEG_EST    $50
COD_PRI_TOP_OF_TER_EST    $50
COD_SEGUNDA_TOP_OFERTA    $50
COD_SEGUNDA_TOP_OFERTA_SEG_EST    $50
COD_SEGUNDA_TOP_OFERTA_TER_EST    $40
COD_TERCEIRA_TOP_OFERTA    $50
COD_TER_TOP_OF_SEG_EST    $50
COD_TER_TOP_OF_TER_EST    $10
NUM_ALEATORIO    8
GRUPO_TESTE    $10
DELTA_HIER_VOZ_TOP1_PRI_EST    8
DELTA_HIER_VOZ_TOP1_SEG_EST    8
DELTA_HIER_VOZ_TOP1_TER_EST    8
DELTA_HIERARQUIA_DADOS_PRI_EST    8
DELTA_HIERARQUIA_DADOS_SEG_EST    8
DELTA_HIERARQUIA_DADOS_TER_EST    8
DELTA_HIERARQUIA_BL_PRI_EST    8
DELTA_HIERARQUIA_BL_SEG_EST    8
DELTA_HIERARQUIA_BL_TER_EST    8
DELTA_HIERARQUIA_TV_PRI_EST    8
DELTA_HIERARQUIA_TV_SEG_EST    8
DELTA_HIERARQUIA_TV_TER_EST    8
OFERTA_FILTRADA_1_EST1    8
OFERTA_FILTRADA_1_EST2    8
OFERTA_FILTRADA_2_EST1    8
OFERTA_FILTRADA_2_EST2    8
CAT_OFERTA_PRI_TOP_OF_PRI_EST    $30
CAT_OFERTA_SEG_TOP_OF_PRI_EST    $30
CAT_OFERTA_TER_TOP_OF_PRI_EST    $30
CAT_OFERTA_PRI_TOP_OF_SEG_EST    $30
CAT_OFERTA_SEG_TOP_OF_SEG_EST    $30
CAT_OFERTA_TER_TOP_OF_SEG_EST    $30
VAL_ASS_VELOX_ANTES    8
VAL_ASS_VELOX_DEPOIS    8
VAL_SVA_VELOX_ANTES    8
VAL_SVA_VELOX_DEPOIS    8
IND_OFERTA_EMPACOTAMENTO    $10
POSSE_CONTEUDOON_ANTES    $30
POSSE_CONTEUDOON_DEPOIS    $10
POSSE_CONTEUDOON_BENEF_ANTES    $70
POSSE_CONTEUDOON_BENEF_DEPOIS    $70
IND_PA_GRATIS    8
IND_ROBOTICS    8
        COD_QUARTA_TOP_OFERTA $ 1
        NOME_PAC_PFC_DEPOIS $ 1
        QUARTA_TOP_OFERTA_APRESENTADA $ 1
        SEGMENTACAO_OFERTA_ACEITA $ 1
        VAL_DADOS_QUARTA_TOP_OFERTA   8
        VAL_FIXO_QUARTA_TOP_OFERTA   8
        VAL_MV_QUARTA_TOP_OFERTA   8
        VAL_OF_QUARTA_TOP_OFERTA   8
        VAL_VELOX_QUARTA_TOP_OFERTA   8
        VAL_VOZ_QUARTA_TOP_OFERTA   8
        QTE_RECARGA_ANTES $ 1
        QTE_RECARGA_DEPOIS $ 1
        TOP_OFERTA_1_SEGMENTACAO $ 1
        TOP_OFERTA_2_SEGMENTACAO $ 1
        TOP_OFERTA_3_SEGMENTACAO $ 1
        TOP_OFERTA_4_SEGMENTACAO $ 1
        TOP_OFERTA_1_GASTOPROPOSTO $ 1
        TOP_OFERTA_2_GASTOPROPOSTO $ 1
        TOP_OFERTA_3_GASTOPROPOSTO $ 1
        TOP_OFERTA_4_GASTOPROPOSTO $ 1
        VAL_TV_QUARTA_TOP_OFERTA $ 1
        IND_ROBOTICS_0001   8
        IND_DISP_FIBRA     8
        TEC_OFERTA_FXBL_ACEITA $ 5
        TEC_OFERTA_TV_ACEITA $ 5
        IND_FIBRA_TOP      8
        TP_TEC_FXBL_POSSE $ 5
        TP_TEC_TV_POSSE  $ 5 ;
    LABEL
        IND_ROBOTICS_0001 = "IND_ROBOTICS_II" ;

FORMAT

ANOMES    BEST10.
CPF_FLAG    $CHAR20.
UCID    BEST20.
ID_BUNDLE    $CHAR10.
VAL_ID_BUNDLE   $CHAR8.
NUM_CPF_CNPJ    BEST20.
NUM_CPF_DIGITADO_CHAMADA    $CHAR20.
NUM_CPF_INFORMADO    $CHAR20.
ID_CPF_FICTICIO    $CHAR20.
DDD_TELEFONE    BEST20.
ID_TERMINAL    $CHAR20.
TP_PRODUTO_OITOTAL    $CHAR20.
BUNDLE_FINAL    $CHAR20.
CELULA_OPERADOR    $CHAR10.
NOME_GRUPO_OPERADOR    $CHAR30.
ID_OPERADOR    $CHAR10.
NOME_OPERADOR    $CHAR50.
LOGIN_AGENTE_CHAMADA    $CHAR10.
DT_LIGACAO    DDMMYY8.
HORARIO_LIGACAO TIME8.
DT_CRIACAO    $CHAR20.
COD_UF    $CHAR10.
NOME_CLIENTE    $CHAR50.
ID_REGISTRO_CHAMADA    BEST20.
TP_CHAMADA    $CHAR20.
COD_REGIAO    $CHAR10.
CLUSTER_CLIENTE    $CHAR99.
NUM_GRUPO_CLUSTER    BEST20.
MAX_VELOC_VELOX_DISPONIVEL    BEST20.
MAX_VELOC_VELOX_CONSULTADA    BEST20.
TEMPO_VIG_CONTR_FIDEL_OITOTAL    BEST20.
TEMPO_VIG_CONTR_FIDEL_TV    BEST20.
TEMPO_VIG_CONTR_FIDEL_MV    BEST20.
QTD_DIAS_ATRASO_PAG_OIT    BEST20.
QTD_DIAS_ATRASO_PAG_TV    BEST20.
QTD_DIAS_ATRASO_PAG_MV    BEST20.
MOTIVO_LIGACAO_CATEGORIA    $CHAR50.
MOTIVO_LIGACAO_NOME    $CHAR50.
NUM_CONTRATO_TV_ASSOCIADO    BEST20.
TP_CONTRATO_TV    $CHAR20.
NUM_TERMINAL_MV_ASSOCIADO    $CHAR20.
SEM_OFERTA_1    $CHAR20.
SEM_OFERTA_2    $CHAR20.
RESULTADO_DA_CHAMADA    $CHAR20.
RESULTADO    $CHAR20.
DETALHE_MIGDOWN_CANCEL    $CHAR50.
PRODUTOS_MANTIDOS_ALONE    $CHAR20.
PRODUTOS_CANCELADOS    $CHAR20.
DETALHE_RESULTADO_DA_CHAMADA    $CHAR60.
STATUS_FINAL_FIXO    $CHAR40.
STATUS_FINAL_BANDA_LARGA    $CHAR40.
STATUS_FINAL_TV    $CHAR40.
STATUS_FINAL_MOVEL_TITULAR    $CHAR40.
DETALHE_STATUS_FINAL_FIXO    $CHAR40.
DETALHE_STATUS_FINAL_BL    $CHAR40.
DETALHE_STATUS_FINAL_TV    $CHAR40.
DETALHE_STATUS_FINAL_MV    $CHAR40.
DETALHE_CHAMADA_IMPRODUTIVA    $CHAR20.
RESULTADO_ATENDIMENTO_N28    $CHAR30.
NUM_PRIMEIRO_CONTATO    BEST20.
NUM_SEGUNDO_CONTATO    $CHAR20.
POSSE_DACC    $CHAR10.
NOVO_DACC    $CHAR10.
POSSE_CONTA_ONLINE    BEST20.
NOVO_CONTA_ONLINE    $CHAR10.
EMAIL_ENVIO    $CHAR40.
NOME_OFERTA_ACEITA    $CHAR70.
NIVEL_PRECO_OFERTA_ACEITA    $CHAR10.
IND_FIDELIDADE_OFERTA    BEST20.
CATEGORIA_OFERTA    $CHAR30.
CATEGORIA_RV_OFERTA    BEST20.
STATUS_ULTIMA_OFERTA    $CHAR10.
ARPU_OITOTAL_ANTES    COMMAX8.2
ARPU_OITOTAL_DEPOIS    COMMAX8.2
ARPU_TARGET    COMMAX8.2
ARPU_LIGACAO    COMMAX8.2
ARPU_RECEITA_ANTES    COMMAX8.2
ARPU_RECEITA_DEPOIS    COMMAX8.2
ARPU_FIXO_ANTES    COMMAX8.2
ARPU_FIXO_DEPOIS    COMMAX8.2
ARPU_RECARGA_ANTES    COMMAX8.2
ARPU_RECARGA_DEPOIS    COMMAX8.2
ARPU_VELOX_ANTES    COMMAX8.2
ARPU_VELOX_DEPOIS    COMMAX8.2
ARPU_TV_ANTES    COMMAX8.2
ARPU_TV_DEPOIS    COMMAX8.2
ARPU_MV_ANTES    COMMAX8.2
ARPU_MV_DEPOIS    COMMAX8.2
PACOTE_FIXO_ANTES    $CHAR30.
PACOTE_FIXO_DEPOIS    $CHAR30.
NOME_PAC_FIXO_ANTES    $CHAR30.
NOME_PAC_FIXO_DEPOIS    $CHAR30.
NOME_PAC_FIXO_LD_ANTES    $CHAR10.
NOME_PAC_FIXO_LD_DEPOIS    $CHAR10.
NOME_PAC_FIXO_VC_ANTES    $CHAR10.
NOME_PAC_FIXO_VC_DEPOIS    $CHAR10.
NOME_PAC_FIXO_SD_ANTES    $CHAR20.
NOME_PAC_FIXO_SD_DEPOIS    $CHAR20.
QTE_RECARGA_AUTO_01    BEST20.
QTE_RECARGA_AUTO_10    BEST20.
QTE_RECARGA_AUTO_15    BEST20.
QTE_RECARGA_AUTO_20    BEST20.
QTE_RECARGA_AUTO_01_DEPOIS    BEST20.
QTE_RECARGA_AUTO_10_DEPOIS    BEST20.
QTE_RECARGA_AUTO_15_DEPOIS    BEST20.
QTE_RECARGA_AUTO_20_DEPOIS    BEST20.
VAL_ASS_FIXO_ANTES    COMMAX8.2
VAL_ASS_FIXO_DEPOIS    COMMAX8.2
VAL_ASS_FIXO_SD_ANTES    COMMAX8.2
VAL_ASS_FIXO_SD_DEPOIS    COMMAX8.2
VAL_ASS_FIXO_LD_ANTES    COMMAX8.2
VAL_ASS_FIXO_LD_DEPOIS    COMMAX8.2
VAL_ASS_FIXO_VC_ANTES    COMMAX8.2
VAL_ASS_FIXO_VC_DEPOIS    COMMAX8.2
VAL_EXC_FIXO_LOC_FF_ANTES    COMMAX8.2
VAL_EXC_FIXO_LOC_FM_ANTES    COMMAX8.2
VAL_EXC_FIXO_LOC_FMOUT_ANTES    COMMAX8.2
VAL_EXC_FIXO_LD_31_ANTES    COMMAX8.2
VAL_RECARGA_PRI_TOP_OF    COMMAX8.2
VAL_RECARGA_PRI_TOP_OF_SEG_EST    COMMAX8.2
VAL_RECARGA_PRI_TOP_OF_TER_EST    COMMAX8.2
VAL_RECARGA_SEGUNDA_TOP_OFERTA    COMMAX8.2
VAL_RECARGA_SEG_TOP_OF_SEG_EST    COMMAX8.2
VAL_RECARGA_SEG_TOP_OF_TER_EST    COMMAX8.2
VAL_RECARGA_TER_TOP_OF    COMMAX8.2
VAL_RECARGA_TER_TOP_OF_SEG_EST    COMMAX8.2
VAL_RECARGA_TER_TOP_OF_TER_EST    COMMAX8.2
VAL_FIXO_PRIMEIRA_TOP_OFERTA    COMMAX8.2
VAL_FIXO_PRI_TOP_OF_SEG_EST    COMMAX8.2
VAL_FIXO_PRI_TOP_OF_TER_EST    COMMAX8.2
VAL_FIXO_SEGUNDA_TOP_OFERTA    COMMAX8.2
VAL_FIXO_SEG_TOP_OF_SEG_EST    COMMAX8.2
VAL_FIXO_SEG_TOP_OF_TER_EST    COMMAX8.2
VAL_FIXO_TERCEIRA_TOP_OFERTA    COMMAX8.2
VAL_FIXO_TER_TOP_OF_SEG_EST    COMMAX8.2
VAL_FIXO_TER_TOP_OF_TER_EST    COMMAX8.2
VAL_TAD_FIXO    COMMAX8.2
NOME_PAC_VELOX_ANTES    $CHAR10.
NOME_PAC_VELOX_DEPOIS    $CHAR10.
NOME_PAC_BLM_ANTES    $CHAR10.
NOME_PAC_BLM_DEPOIS    $CHAR10.
VELOC_VELOX_OFERTA_ACEITA    $CHAR40.
VAL_VELOX_PRIMEIRA_TOP_OFERTA    COMMAX8.2
VAL_VELOX_PRI_TOP_OF_SEG_EST    COMMAX8.2
VAL_VELOX_PRI_TOP_OF_TER_EST    COMMAX8.2
VAL_VELOX_SEGUNDA_TOP_OFERTA    COMMAX8.2
VAL_VELOX_SEG_TOP_OF_SEG_EST    COMMAX8.2
VAL_VELOX_SEG_TOP_OF_TER_EST    COMMAX8.2
VAL_VELOX_TERCEIRA_TOP_OFERTA    COMMAX8.2
VAL_VELOX_TER_TOP_OF_SEG_EST    COMMAX8.2
VAL_VELOX_TER_TOP_OF_TER_EST    COMMAX8.2
VAL_THAB_VELOX    COMMAX8.2
IND_POSSE_COMBATE    BEST20.
IND_POSSE_ETNICO    BEST20.
IND_POSSE_PFC    BEST20.
IND_POSSE_PLAYBOY    BEST20.
IND_POSSE_PLAYBOY_SEXYHOT    BEST20.
IND_POSSE_PRIVE    BEST20.
IND_POSSE_SEXYHOT    BEST20.
IND_POSSE_COMBATE_DEPOIS    BEST20.
IND_POSSE_ETNICO_DEPOIS    BEST20.
IND_POSSE_PFC_DEPOIS    BEST20.
IND_POSSE_PLAYBOY_DEPOIS    BEST20.
IND_POSSE_PRIVE_DEPOIS    BEST20.
IND_POSSE_SEXYHOT_DEPOIS    BEST20.
IND_POSSE_BBB_DEPOIS    BEST20.
IND_POSSE_PLAYBOYSEXHOT_DEPOIS    BEST20.
IND_POSSE_CONTEUDOON_ANTES    BEST20.
IND_POSSE_CONTEUDOON_DEPOIS    $CHAR10.
IND_POSSE_DVR_ANTES    BEST20.
IND_POSSE_DVR_DEPOIS    BEST20.
IND_POSSE_PENVR_ANTES    BEST20.
IND_POSSE_PENVR_DEPOIS    BEST20.
QTD_PONTOS_ADIC_TV_ANTES    BEST20.
QTD_PONTOS_ADIC_TV_DEPOIS    BEST20.
TP_SATELITE_ANTES    $CHAR10.
TP_SATELITE_DEPOIS    $CHAR10.
NOME_PAC_TV_ANTES    $CHAR30.
NOME_PAC_TV_DEPOIS    $CHAR30.
NOME_DEGUSTACAO_TV_DEPOIS    $CHAR20.
PERIODO_DEGUSTACAO_TV_DEPOIS    BEST20.
VAL_PLANO_TV_ANTES    COMMAX8.2
VAL_PLANO_TV_DEPOIS    COMMAX8.2
VAL_LA_CARTE_ANTES    COMMAX8.2
VAL_LA_CARTE_DEPOIS    COMMAX8.2
VAL_PONTOS_ADIC_ANTES    COMMAX8.2
VAL_PONTOS_ADIC_DEPOIS    COMMAX8.2
VAL_PENVR_ANTES    COMMAX8.2
VAL_PENVR_DEPOIS    COMMAX8.2
VAL_TV_PRIMEIRA_TOP_OFERTA    COMMAX8.2
VAL_TV_PRI_TOP_OF_SEG_EST    COMMAX8.2
VAL_TV_PRI_TOP_OF_TER_EST    COMMAX8.2
VAL_TV_SEGUNDA_TOP_OFERTA    COMMAX8.2
VAL_TV_SEG_TOP_OF_SEG_EST    COMMAX8.2
VAL_TV_SEG_TOP_OF_TER_EST    COMMAX8.2
VAL_TV_TERCEIRA_TOP_OFERTA    COMMAX8.2
VAL_TV_TER_TOP_OF_SEG_EST    COMMAX8.2
VAL_TV_TER_TOP_OF_TER_EST    COMMAX8.2
VAL_THAB_TV    COMMAX8.2
NOME_PAC_MV_VOZ_ANTES    $CHAR50.
NOME_PAC_MV_VOZ_DEPOIS    $CHAR50.
NOME_PAC_MV_DADOS_TIT_ANTES    $CHAR10.
NOME_PAC_MV_DADOS_TIT_DEPOIS    $CHAR10.
NOME_PAC_MV_LD_ANTES    $CHAR20.
NOME_PAC_MV_LD_DEPOIS    $CHAR20.
VAL_ASS_MV_VOZ_ANTES    COMMAX8.2
VAL_ASS_MV_VOZ_DEPOIS    COMMAX8.2
VAL_ASS_MV_DADOS_TIT_ANTES    COMMAX8.2
VAL_ASS_MV_DADOS_TIT_DEPOIS    COMMAX8.2
VAL_ASS_MV_LD_ANTES    COMMAX8.2
VAL_ASS_MV_LD_DEPOIS    COMMAX8.2
VAL_ASS_MV_DADOS_DEP_ANTES    COMMAX8.2
VAL_ASS_MV_DADOS_DEP_DEPOIS    COMMAX8.2
VAL_ASS_MV_DEP_ANTES    COMMAX8.2
VAL_ASS_MV_DEP_DEPOIS    COMMAX8.2
VAL_EXC_LD_ON_MV_OI_ANTES    COMMAX8.2
VAL_EXC_LD_OFF_MV_OI_ANTES    COMMAX8.2
VAL_EXC_LD_ON_MV_OUT_ANTES    COMMAX8.2
VAL_EXC_LD_OFF_MV_OUT_ANTES    COMMAX8.2
VAL_EXC_LOCAL_ON_MV_ANTES    COMMAX8.2
VAL_EXC_LOCAL_OFF_MV_ANTES    COMMAX8.2
VAL_EXC_SMS_MV_ANTES    COMMAX8.2
VAL_EXC_DADOS_MV_ANTES    COMMAX8.2
VAL_EXC_OUTROS_MV_ANTES    COMMAX8.2
VAL_VOZ_PRIMEIRA_TOP_OFERTA    COMMAX8.2
VAL_VOZ_PRI_TOP_OF_SEG_EST    COMMAX8.2
VAL_VOZ_PRI_TOP_OF_TER_EST    COMMAX8.2
VAL_DADOS_PRIMEIRA_TOP_OFERTA    COMMAX8.2
VAL_DADOS_PRI_TOP_OF_SEG_EST    COMMAX8.2
VAL_DADOS_PRI_TOP_OF_TER_EST    COMMAX8.2
VAL_MOVEL_PRIMEIRA_TOP_OFERTA    COMMAX8.2
VAL_MOVEL_PRI_TOP_OF_SEG_EST    COMMAX8.2
VAL_MOVEL_PRI_TOP_OF_TER_EST    COMMAX8.2
VAL_VOZ_SEGUNDA_TOP_OFERTA    COMMAX8.2
VAL_VOZ_SEG_TOP_OF_SEG_EST    COMMAX8.2
VAL_VOZ_SEG_TOP_OF_TER_EST    COMMAX8.2
VAL_DADOS_SEGUNDA_TOP_OFERTA    COMMAX8.2
VAL_DADOS_SEG_TOP_OF_SEG_EST    COMMAX8.2
VAL_DADOS_SEG_TOP_OF_TER_EST    COMMAX8.2
VAL_MOVEL_SEGUNDA_TOP_OFERTA    COMMAX8.2
VAL_MOVEL_SEG_TOP_OF_SEG_EST    COMMAX8.2
VAL_MOVEL_SEG_TOP_OF_TER_EST    COMMAX8.2
VAL_VOZ_TERCEIRA_TOP_OFERTA    COMMAX8.2
VAL_VOZ_TER_TOP_OF_SEG_EST    COMMAX8.2
VAL_VOZ_TER_TOP_OF_TER_EST    COMMAX8.2
VAL_DADOS_TERCEIRA_TOP_OFERTA    COMMAX8.2
VAL_DADOS_TER_TOP_OF_SEG_EST    COMMAX8.2
VAL_DADOS_TER_TOP_OF_TER_EST    COMMAX8.2
VAL_MOVEL_TERCEIRA_TOP_OFERTA    COMMAX8.2
VAL_MOVEL_TER_TOP_OF_SEG_EST    COMMAX8.2
VAL_MOVEL_TER_TOP_OF_TER_EST    COMMAX8.2
VAL_OFERTA_PRIMEIRA_TOP_OFERTA    COMMAX8.2
VAL_OF_PRI_TOP_OF_SEG_EST    COMMAX8.2
VAL_OF_PRI_TOP_OF_TER_EST    COMMAX8.2
VAL_OFERTA_SEGUNDA_TOP_OFERTA    COMMAX8.2
VAL_OF_SEG_TOP_OF_SEG_EST    COMMAX8.2
VAL_OF_SEG_TOP_OF_TER_EST    COMMAX8.2
VAL_OFERTA_TERCEIRA_TOP_OFERTA    COMMAX8.2
VAL_OF_TER_TOP_OF_SEG_EST    COMMAX8.2
VAL_OF_TER_TOP_OF_TER_EST    COMMAX8.2
COD_PLANO_ACEITA_OITOTAL    $CHAR50.
COD_CAMPANHA_ACEITA_OITOTAL    $CHAR50.
COD_OFERTA_ACEITA_OITOTAL    $CHAR50.
COD_CAMPANHA_ACEITA_FIXO    $CHAR60.
COD_OFERTA_ACEITA_FIXO    $CHAR60.
COD_CAMPANHA_ACEITA_VELOX    $CHAR50.
COD_OFERTA_ACEITA_VELOX    $CHAR10.
COD_CAMPANHA_ACEITA_BLM    $CHAR10.
COD_OFERTA_ACEITA_BLM    $CHAR10.
COD_CAMPANHA_ACEITA_TV    $CHAR40.
COD_OFERTA_ACEITA_TV    $CHAR10.
COD_CAMPANHA_ACEITA_VOZ_MV    $CHAR50.
COD_OFERTA_ACEITA_VOZ_MV    $CHAR50.
COD_CAMPANHA_ACEITA_DADOS_MV    $CHAR10.
COD_OFERTA_ACEITA_DADOS_MV    $CHAR10.
QTE_DEPENDENTES_ANTES    BEST20.
QTE_DEPENDENTES_DEPOIS    BEST20.
FRAN_BLM_ANTES    $CHAR10.
FRAN_BLM_DEPOIS    $CHAR10.
RESULTADO_ATENDIMENTO_N10    $CHAR10.
RESULTADO_ATENDIMENTO_N11    $CHAR10.
RESULTADO_ATENDIMENTO_N12    $CHAR10.
RESULTADO_ATENDIMENTO_N13    $CHAR20.
RESULTADO_ATENDIMENTO_N14    $CHAR20.
RESULTADO_ATENDIMENTO_N20    BEST20.
RESULTADO_ATENDIMENTO_N21    BEST20.
RESULTADO_ATENDIMENTO_N22    $CHAR10.
RESULTADO_ATENDIMENTO_N23    BEST20.
RESULTADO_ATENDIMENTO_N24    BEST20.
RESULTADO_ATENDIMENTO_N25    $CHAR10.
RESULTADO_ATENDIMENTO_N26    $CHAR20.
RESULTADO_ATENDIMENTO_N27    $CHAR10.
RESULTADO_ATENDIMENTO_N29    $CHAR20.
RESULTADO_ATENDIMENTO_N30    $CHAR20.
RESULTADO_ATENDIMENTO_N31    $CHAR10.
RESULTADO_ATENDIMENTO_N32    $CHAR10.
RESULTADO_ATENDIMENTO_N33    $CHAR10.
RESULTADO_ATENDIMENTO_N34    $CHAR10.
RESULTADO_ATENDIMENTO_N35    $CHAR10.
RESULTADO_ATENDIMENTO_N36    $CHAR10.
RESULTADO_ATENDIMENTO_N37    $CHAR10.
RESULTADO_ATENDIMENTO_N38    $CHAR10.
DELTA_HIERARQUIA_VOZ_ACEITA    $CHAR10.
DELTA_HIERARQUIA_DADOS_ACEITA    BEST20.
DELTA_HIERARQUIA_BL_ACEITA    BEST20.
DELTA_HIERARQUIA_TV_ACEITA    BEST20.
COD_VERSAO_MACRO    $CHAR10.
COD_CLEANUP_ACEITA_BL    $CHAR10.
COD_AGR_ACEITA_FIXO    $CHAR10.
COD_DESCRICAO_ACEITA_FIXO    $CHAR50.
COD_CAMPANHA_VOZ_TOTAL    $CHAR10.
COD_CAMPANHA_PONTO_ADICIONAL    $CHAR40.
COD_CAMPANHA_DEGUSTACAO    $CHAR50.
COD_CAMPANHA_PACOTE_LACARTE    $CHAR30.
PRI_TOP_OF_APRESENTADA    $CHAR70.
PRI_TOP_OF_APRESENTADA_SEG_EST    $CHAR70.
PRI_TOP_OF_APRESENTADA_TER_EST    $CHAR70.
SEGUNDA_TOP_OFERTA_APRESENTADA    $CHAR70.
SEG_TOP_OF_APRESENTADA_SEG_EST    $CHAR70.
SEG_TOP_OF_APRESENTADA_TER_EST    $CHAR30.
TER_TOP_OF_APRESENTADA    $CHAR70.
TER_TOP_OF_APRESENTADA_SEG_EST    $CHAR50.
TER_TOP_OF_APRESENTADA_TER_EST    $CHAR10.
NOME_GUERRA_PRI_TOP_OF    $CHAR99.
NOME_GUERRA_PRI_TOP_OF_SEG_EST    $CHAR99.
NOME_GUERRA_PRI_TOP_OF_TER_EST    $CHAR99.
NOME_GUERRA_SEGUNDA_TOP_OFERTA    $CHAR99.
NOME_GUERRA_SEG_TOP_OF_SEG_EST    $CHAR99.
NOME_GUERRA_SEG_TOP_OF_TER_EST    $CHAR70.
NOME_GUERRA_TER_TOP_OF    $CHAR99.
NOME_GUERRA_TER_TOP_OF_SEG_EST    $CHAR99.
NOME_GUERRA_TER_TOP_OF_TER_EST    $CHAR10.
COD_PRIMEIRA_TOP_OFERTA    $CHAR50.
COD_PRI_TOP_OF_SEG_EST    $CHAR50.
COD_PRI_TOP_OF_TER_EST    $CHAR50.
COD_SEGUNDA_TOP_OFERTA    $CHAR50.
COD_SEGUNDA_TOP_OFERTA_SEG_EST    $CHAR50.
COD_SEGUNDA_TOP_OFERTA_TER_EST    $CHAR40.
COD_TERCEIRA_TOP_OFERTA    $CHAR50.
COD_TER_TOP_OF_SEG_EST    $CHAR50.
COD_TER_TOP_OF_TER_EST    $CHAR10.
NUM_ALEATORIO    COMMAX8.2
GRUPO_TESTE    $CHAR10.
DELTA_HIER_VOZ_TOP1_PRI_EST    BEST20.
DELTA_HIER_VOZ_TOP1_SEG_EST    BEST20.
DELTA_HIER_VOZ_TOP1_TER_EST    BEST20.
DELTA_HIERARQUIA_DADOS_PRI_EST    BEST20.
DELTA_HIERARQUIA_DADOS_SEG_EST    BEST20.
DELTA_HIERARQUIA_DADOS_TER_EST    BEST20.
DELTA_HIERARQUIA_BL_PRI_EST    BEST20.
DELTA_HIERARQUIA_BL_SEG_EST    BEST20.
DELTA_HIERARQUIA_BL_TER_EST    BEST20.
DELTA_HIERARQUIA_TV_PRI_EST    BEST20.
DELTA_HIERARQUIA_TV_SEG_EST    BEST20.
DELTA_HIERARQUIA_TV_TER_EST    BEST20.
OFERTA_FILTRADA_1_EST1    BEST20.
OFERTA_FILTRADA_1_EST2    BEST20.
OFERTA_FILTRADA_2_EST1    BEST20.
OFERTA_FILTRADA_2_EST2    BEST20.
CAT_OFERTA_PRI_TOP_OF_PRI_EST    $CHAR30.
CAT_OFERTA_SEG_TOP_OF_PRI_EST    $CHAR30.
CAT_OFERTA_TER_TOP_OF_PRI_EST    $CHAR30.
CAT_OFERTA_PRI_TOP_OF_SEG_EST    $CHAR30.
CAT_OFERTA_SEG_TOP_OF_SEG_EST    $CHAR30.
CAT_OFERTA_TER_TOP_OF_SEG_EST    $CHAR30.
VAL_ASS_VELOX_ANTES    COMMAX8.2
VAL_ASS_VELOX_DEPOIS    COMMAX8.2
VAL_SVA_VELOX_ANTES    COMMAX8.2
VAL_SVA_VELOX_DEPOIS    COMMAX8.2
IND_OFERTA_EMPACOTAMENTO    $CHAR10.
POSSE_CONTEUDOON_ANTES    $CHAR30.
POSSE_CONTEUDOON_DEPOIS    $CHAR10.
POSSE_CONTEUDOON_BENEF_ANTES    $CHAR70.
POSSE_CONTEUDOON_BENEF_DEPOIS    $CHAR70.
IND_PA_GRATIS    BEST20.
IND_ROBOTICS    BEST20.
        COD_QUARTA_TOP_OFERTA $CHAR1.
        NOME_PAC_PFC_DEPOIS $CHAR1.
        QUARTA_TOP_OFERTA_APRESENTADA $CHAR1.
        SEGMENTACAO_OFERTA_ACEITA $CHAR1.
        VAL_DADOS_QUARTA_TOP_OFERTA BEST1.
        VAL_FIXO_QUARTA_TOP_OFERTA BEST1.
        VAL_MV_QUARTA_TOP_OFERTA BEST1.
        VAL_OF_QUARTA_TOP_OFERTA BEST1.
        VAL_VELOX_QUARTA_TOP_OFERTA BEST1.
        VAL_VOZ_QUARTA_TOP_OFERTA BEST1.
        QTE_RECARGA_ANTES $CHAR1.
        QTE_RECARGA_DEPOIS $CHAR1.
        TOP_OFERTA_1_SEGMENTACAO $CHAR1.
        TOP_OFERTA_2_SEGMENTACAO $CHAR1.
        TOP_OFERTA_3_SEGMENTACAO $CHAR1.
        TOP_OFERTA_4_SEGMENTACAO $CHAR1.
        TOP_OFERTA_1_GASTOPROPOSTO $CHAR1.
        TOP_OFERTA_2_GASTOPROPOSTO $CHAR1.
        TOP_OFERTA_3_GASTOPROPOSTO $CHAR1.
        TOP_OFERTA_4_GASTOPROPOSTO $CHAR1.
        VAL_TV_QUARTA_TOP_OFERTA $CHAR1.
        IND_ROBOTICS_II BEST20.
        IND_DISP_FIBRA   BEST20.
        TEC_OFERTA_FXBL_ACEITA $CHAR5.
        TEC_OFERTA_TV_ACEITA $CHAR5.
        IND_FIBRA_TOP    BEST20.
        TP_TEC_FXBL_POSSE $CHAR5.
        TP_TEC_TV_POSSE  $CHAR5. ;

INFORMAT

ANOMES    BEST10.
CPF_FLAG    $CHAR20.
UCID    BEST20.
ID_BUNDLE    $CHAR10.
VAL_ID_BUNDLE   $CHAR8.
NUM_CPF_CNPJ    BEST20.
NUM_CPF_DIGITADO_CHAMADA    $CHAR20.
NUM_CPF_INFORMADO    $CHAR20.
ID_CPF_FICTICIO    $CHAR20.
DDD_TELEFONE    BEST20.
ID_TERMINAL    $CHAR20.
TP_PRODUTO_OITOTAL    $CHAR20.
BUNDLE_FINAL    $CHAR20.
CELULA_OPERADOR    $CHAR10.
NOME_GRUPO_OPERADOR    $CHAR30.
ID_OPERADOR    $CHAR10.
NOME_OPERADOR    $CHAR50.
LOGIN_AGENTE_CHAMADA    $CHAR10.
DT_LIGACAO    DATE9.
HORARIO_LIGACAO TIME8.
DT_CRIACAO    $CHAR20.
COD_UF    $CHAR10.
NOME_CLIENTE    $CHAR50.
ID_REGISTRO_CHAMADA    BEST20.
TP_CHAMADA    $CHAR20.
COD_REGIAO    $CHAR10.
CLUSTER_CLIENTE    $CHAR99.
NUM_GRUPO_CLUSTER    BEST20.
MAX_VELOC_VELOX_DISPONIVEL    BEST20.
MAX_VELOC_VELOX_CONSULTADA    BEST20.
TEMPO_VIG_CONTR_FIDEL_OITOTAL    BEST20.
TEMPO_VIG_CONTR_FIDEL_TV    BEST20.
TEMPO_VIG_CONTR_FIDEL_MV    BEST20.
QTD_DIAS_ATRASO_PAG_OIT    BEST20.
QTD_DIAS_ATRASO_PAG_TV    BEST20.
QTD_DIAS_ATRASO_PAG_MV    BEST20.
MOTIVO_LIGACAO_CATEGORIA    $CHAR50.
MOTIVO_LIGACAO_NOME    $CHAR50.
NUM_CONTRATO_TV_ASSOCIADO    BEST20.
TP_CONTRATO_TV    $CHAR20.
NUM_TERMINAL_MV_ASSOCIADO    $CHAR20.
SEM_OFERTA_1    $CHAR20.
SEM_OFERTA_2    $CHAR20.
RESULTADO_DA_CHAMADA    $CHAR20.
RESULTADO    $CHAR20.
DETALHE_MIGDOWN_CANCEL    $CHAR50.
PRODUTOS_MANTIDOS_ALONE    $CHAR20.
PRODUTOS_CANCELADOS    $CHAR20.
DETALHE_RESULTADO_DA_CHAMADA    $CHAR60.
STATUS_FINAL_FIXO    $CHAR40.
STATUS_FINAL_BANDA_LARGA    $CHAR40.
STATUS_FINAL_TV    $CHAR40.
STATUS_FINAL_MOVEL_TITULAR    $CHAR40.
DETALHE_STATUS_FINAL_FIXO    $CHAR40.
DETALHE_STATUS_FINAL_BL    $CHAR40.
DETALHE_STATUS_FINAL_TV    $CHAR40.
DETALHE_STATUS_FINAL_MV    $CHAR40.
DETALHE_CHAMADA_IMPRODUTIVA    $CHAR20.
RESULTADO_ATENDIMENTO_N28    $CHAR30.
NUM_PRIMEIRO_CONTATO    BEST20.
NUM_SEGUNDO_CONTATO    $CHAR20.
POSSE_DACC    $CHAR10.
NOVO_DACC    $CHAR10.
POSSE_CONTA_ONLINE    BEST20.
NOVO_CONTA_ONLINE    $CHAR10.
EMAIL_ENVIO    $CHAR40.
NOME_OFERTA_ACEITA    $CHAR70.
NIVEL_PRECO_OFERTA_ACEITA    $CHAR10.
IND_FIDELIDADE_OFERTA    BEST20.
CATEGORIA_OFERTA    $CHAR30.
CATEGORIA_RV_OFERTA    BEST20.
STATUS_ULTIMA_OFERTA    $CHAR10.
ARPU_OITOTAL_ANTES    COMMAX12.0
ARPU_OITOTAL_DEPOIS    COMMAX12.0
ARPU_TARGET    COMMAX12.0
ARPU_LIGACAO    COMMAX12.0
ARPU_RECEITA_ANTES    COMMAX12.0
ARPU_RECEITA_DEPOIS    COMMAX12.0
ARPU_FIXO_ANTES    COMMAX12.0
ARPU_FIXO_DEPOIS    COMMAX12.0
ARPU_RECARGA_ANTES    COMMAX12.0
ARPU_RECARGA_DEPOIS    COMMAX12.0
ARPU_VELOX_ANTES    COMMAX12.0
ARPU_VELOX_DEPOIS    COMMAX12.0
ARPU_TV_ANTES    COMMAX12.0
ARPU_TV_DEPOIS    COMMAX12.0
ARPU_MV_ANTES    COMMAX12.0
ARPU_MV_DEPOIS    COMMAX12.0
PACOTE_FIXO_ANTES    $CHAR30.
PACOTE_FIXO_DEPOIS    $CHAR30.
NOME_PAC_FIXO_ANTES    $CHAR30.
NOME_PAC_FIXO_DEPOIS    $CHAR30.
NOME_PAC_FIXO_LD_ANTES    $CHAR10.
NOME_PAC_FIXO_LD_DEPOIS    $CHAR10.
NOME_PAC_FIXO_VC_ANTES    $CHAR10.
NOME_PAC_FIXO_VC_DEPOIS    $CHAR10.
NOME_PAC_FIXO_SD_ANTES    $CHAR20.
NOME_PAC_FIXO_SD_DEPOIS    $CHAR20.
QTE_RECARGA_AUTO_01    BEST20.
QTE_RECARGA_AUTO_10    BEST20.
QTE_RECARGA_AUTO_15    BEST20.
QTE_RECARGA_AUTO_20    BEST20.
QTE_RECARGA_AUTO_01_DEPOIS    BEST20.
QTE_RECARGA_AUTO_10_DEPOIS    BEST20.
QTE_RECARGA_AUTO_15_DEPOIS    BEST20.
QTE_RECARGA_AUTO_20_DEPOIS    BEST20.
VAL_ASS_FIXO_ANTES    COMMAX12.0
VAL_ASS_FIXO_DEPOIS    COMMAX12.0
VAL_ASS_FIXO_SD_ANTES    COMMAX12.0
VAL_ASS_FIXO_SD_DEPOIS    COMMAX12.0
VAL_ASS_FIXO_LD_ANTES    COMMAX12.0
VAL_ASS_FIXO_LD_DEPOIS    COMMAX12.0
VAL_ASS_FIXO_VC_ANTES    COMMAX12.0
VAL_ASS_FIXO_VC_DEPOIS    COMMAX12.0
VAL_EXC_FIXO_LOC_FF_ANTES    COMMAX12.0
VAL_EXC_FIXO_LOC_FM_ANTES    COMMAX12.0
VAL_EXC_FIXO_LOC_FMOUT_ANTES    COMMAX12.0
VAL_EXC_FIXO_LD_31_ANTES    COMMAX12.0
VAL_RECARGA_PRI_TOP_OF    COMMAX12.0
VAL_RECARGA_PRI_TOP_OF_SEG_EST    COMMAX12.0
VAL_RECARGA_PRI_TOP_OF_TER_EST    COMMAX12.0
VAL_RECARGA_SEGUNDA_TOP_OFERTA    COMMAX12.0
VAL_RECARGA_SEG_TOP_OF_SEG_EST    COMMAX12.0
VAL_RECARGA_SEG_TOP_OF_TER_EST    COMMAX12.0
VAL_RECARGA_TER_TOP_OF    COMMAX12.0
VAL_RECARGA_TER_TOP_OF_SEG_EST    COMMAX12.0
VAL_RECARGA_TER_TOP_OF_TER_EST    COMMAX12.0
VAL_FIXO_PRIMEIRA_TOP_OFERTA    COMMAX12.0
VAL_FIXO_PRI_TOP_OF_SEG_EST    COMMAX12.0
VAL_FIXO_PRI_TOP_OF_TER_EST    COMMAX12.0
VAL_FIXO_SEGUNDA_TOP_OFERTA    COMMAX12.0
VAL_FIXO_SEG_TOP_OF_SEG_EST    COMMAX12.0
VAL_FIXO_SEG_TOP_OF_TER_EST    COMMAX12.0
VAL_FIXO_TERCEIRA_TOP_OFERTA    COMMAX12.0
VAL_FIXO_TER_TOP_OF_SEG_EST    COMMAX12.0
VAL_FIXO_TER_TOP_OF_TER_EST    COMMAX12.0
VAL_TAD_FIXO    COMMAX12.0
NOME_PAC_VELOX_ANTES    $CHAR10.
NOME_PAC_VELOX_DEPOIS    $CHAR10.
NOME_PAC_BLM_ANTES    $CHAR10.
NOME_PAC_BLM_DEPOIS    $CHAR10.
VELOC_VELOX_OFERTA_ACEITA    $CHAR40.
VAL_VELOX_PRIMEIRA_TOP_OFERTA    COMMAX12.0
VAL_VELOX_PRI_TOP_OF_SEG_EST    COMMAX12.0
VAL_VELOX_PRI_TOP_OF_TER_EST    COMMAX12.0
VAL_VELOX_SEGUNDA_TOP_OFERTA    COMMAX12.0
VAL_VELOX_SEG_TOP_OF_SEG_EST    COMMAX12.0
VAL_VELOX_SEG_TOP_OF_TER_EST    COMMAX12.0
VAL_VELOX_TERCEIRA_TOP_OFERTA    COMMAX12.0
VAL_VELOX_TER_TOP_OF_SEG_EST    COMMAX12.0
VAL_VELOX_TER_TOP_OF_TER_EST    COMMAX12.0
VAL_THAB_VELOX    COMMAX12.0
IND_POSSE_COMBATE    BEST20.
IND_POSSE_ETNICO    BEST20.
IND_POSSE_PFC    BEST20.
IND_POSSE_PLAYBOY    BEST20.
IND_POSSE_PLAYBOY_SEXYHOT    BEST20.
IND_POSSE_PRIVE    BEST20.
IND_POSSE_SEXYHOT    BEST20.
IND_POSSE_COMBATE_DEPOIS    BEST20.
IND_POSSE_ETNICO_DEPOIS    BEST20.
IND_POSSE_PFC_DEPOIS    BEST20.
IND_POSSE_PLAYBOY_DEPOIS    BEST20.
IND_POSSE_PRIVE_DEPOIS    BEST20.
IND_POSSE_SEXYHOT_DEPOIS    BEST20.
IND_POSSE_BBB_DEPOIS    BEST20.
IND_POSSE_PLAYBOYSEXHOT_DEPOIS    BEST20.
IND_POSSE_CONTEUDOON_ANTES    BEST20.
IND_POSSE_CONTEUDOON_DEPOIS    $CHAR10.
IND_POSSE_DVR_ANTES    BEST20.
IND_POSSE_DVR_DEPOIS    BEST20.
IND_POSSE_PENVR_ANTES    BEST20.
IND_POSSE_PENVR_DEPOIS    BEST20.
QTD_PONTOS_ADIC_TV_ANTES    BEST20.
QTD_PONTOS_ADIC_TV_DEPOIS    BEST20.
TP_SATELITE_ANTES    $CHAR10.
TP_SATELITE_DEPOIS    $CHAR10.
NOME_PAC_TV_ANTES    $CHAR30.
NOME_PAC_TV_DEPOIS    $CHAR30.
NOME_DEGUSTACAO_TV_DEPOIS    $CHAR20.
PERIODO_DEGUSTACAO_TV_DEPOIS    BEST20.
VAL_PLANO_TV_ANTES    COMMAX12.0
VAL_PLANO_TV_DEPOIS    COMMAX12.0
VAL_LA_CARTE_ANTES    COMMAX12.0
VAL_LA_CARTE_DEPOIS    COMMAX12.0
VAL_PONTOS_ADIC_ANTES    COMMAX12.0
VAL_PONTOS_ADIC_DEPOIS    COMMAX12.0
VAL_PENVR_ANTES    COMMAX12.0
VAL_PENVR_DEPOIS    COMMAX12.0
VAL_TV_PRIMEIRA_TOP_OFERTA    COMMAX12.0
VAL_TV_PRI_TOP_OF_SEG_EST    COMMAX12.0
VAL_TV_PRI_TOP_OF_TER_EST    COMMAX12.0
VAL_TV_SEGUNDA_TOP_OFERTA    COMMAX12.0
VAL_TV_SEG_TOP_OF_SEG_EST    COMMAX12.0
VAL_TV_SEG_TOP_OF_TER_EST    COMMAX12.0
VAL_TV_TERCEIRA_TOP_OFERTA    COMMAX12.0
VAL_TV_TER_TOP_OF_SEG_EST    COMMAX12.0
VAL_TV_TER_TOP_OF_TER_EST    COMMAX12.0
VAL_THAB_TV    COMMAX12.0
NOME_PAC_MV_VOZ_ANTES    $CHAR50.
NOME_PAC_MV_VOZ_DEPOIS    $CHAR50.
NOME_PAC_MV_DADOS_TIT_ANTES    $CHAR10.
NOME_PAC_MV_DADOS_TIT_DEPOIS    $CHAR10.
NOME_PAC_MV_LD_ANTES    $CHAR20.
NOME_PAC_MV_LD_DEPOIS    $CHAR20.
VAL_ASS_MV_VOZ_ANTES    COMMAX12.0
VAL_ASS_MV_VOZ_DEPOIS    COMMAX12.0
VAL_ASS_MV_DADOS_TIT_ANTES    COMMAX12.0
VAL_ASS_MV_DADOS_TIT_DEPOIS    COMMAX12.0
VAL_ASS_MV_LD_ANTES    COMMAX12.0
VAL_ASS_MV_LD_DEPOIS    COMMAX12.0
VAL_ASS_MV_DADOS_DEP_ANTES    COMMAX12.0
VAL_ASS_MV_DADOS_DEP_DEPOIS    COMMAX12.0
VAL_ASS_MV_DEP_ANTES    COMMAX12.0
VAL_ASS_MV_DEP_DEPOIS    COMMAX12.0
VAL_EXC_LD_ON_MV_OI_ANTES    COMMAX12.0
VAL_EXC_LD_OFF_MV_OI_ANTES    COMMAX12.0
VAL_EXC_LD_ON_MV_OUT_ANTES    COMMAX12.0
VAL_EXC_LD_OFF_MV_OUT_ANTES    COMMAX12.0
VAL_EXC_LOCAL_ON_MV_ANTES    COMMAX12.0
VAL_EXC_LOCAL_OFF_MV_ANTES    COMMAX12.0
VAL_EXC_SMS_MV_ANTES    COMMAX12.0
VAL_EXC_DADOS_MV_ANTES    COMMAX12.0
VAL_EXC_OUTROS_MV_ANTES    COMMAX12.0
VAL_VOZ_PRIMEIRA_TOP_OFERTA    COMMAX12.0
VAL_VOZ_PRI_TOP_OF_SEG_EST    COMMAX12.0
VAL_VOZ_PRI_TOP_OF_TER_EST    COMMAX12.0
VAL_DADOS_PRIMEIRA_TOP_OFERTA    COMMAX12.0
VAL_DADOS_PRI_TOP_OF_SEG_EST    COMMAX12.0
VAL_DADOS_PRI_TOP_OF_TER_EST    COMMAX12.0
VAL_MOVEL_PRIMEIRA_TOP_OFERTA    COMMAX12.0
VAL_MOVEL_PRI_TOP_OF_SEG_EST    COMMAX12.0
VAL_MOVEL_PRI_TOP_OF_TER_EST    COMMAX12.0
VAL_VOZ_SEGUNDA_TOP_OFERTA    COMMAX12.0
VAL_VOZ_SEG_TOP_OF_SEG_EST    COMMAX12.0
VAL_VOZ_SEG_TOP_OF_TER_EST    COMMAX12.0
VAL_DADOS_SEGUNDA_TOP_OFERTA    COMMAX12.0
VAL_DADOS_SEG_TOP_OF_SEG_EST    COMMAX12.0
VAL_DADOS_SEG_TOP_OF_TER_EST    COMMAX12.0
VAL_MOVEL_SEGUNDA_TOP_OFERTA    COMMAX12.0
VAL_MOVEL_SEG_TOP_OF_SEG_EST    COMMAX12.0
VAL_MOVEL_SEG_TOP_OF_TER_EST    COMMAX12.0
VAL_VOZ_TERCEIRA_TOP_OFERTA    COMMAX12.0
VAL_VOZ_TER_TOP_OF_SEG_EST    COMMAX12.0
VAL_VOZ_TER_TOP_OF_TER_EST    COMMAX12.0
VAL_DADOS_TERCEIRA_TOP_OFERTA    COMMAX12.0
VAL_DADOS_TER_TOP_OF_SEG_EST    COMMAX12.0
VAL_DADOS_TER_TOP_OF_TER_EST    COMMAX12.0
VAL_MOVEL_TERCEIRA_TOP_OFERTA    COMMAX12.0
VAL_MOVEL_TER_TOP_OF_SEG_EST    COMMAX12.0
VAL_MOVEL_TER_TOP_OF_TER_EST    COMMAX12.0
VAL_OFERTA_PRIMEIRA_TOP_OFERTA    COMMAX12.0
VAL_OF_PRI_TOP_OF_SEG_EST    COMMAX12.0
VAL_OF_PRI_TOP_OF_TER_EST    COMMAX12.0
VAL_OFERTA_SEGUNDA_TOP_OFERTA    COMMAX12.0
VAL_OF_SEG_TOP_OF_SEG_EST    COMMAX12.0
VAL_OF_SEG_TOP_OF_TER_EST    COMMAX12.0
VAL_OFERTA_TERCEIRA_TOP_OFERTA    COMMAX12.0
VAL_OF_TER_TOP_OF_SEG_EST    COMMAX12.0
VAL_OF_TER_TOP_OF_TER_EST    COMMAX12.0
COD_PLANO_ACEITA_OITOTAL    $CHAR50.
COD_CAMPANHA_ACEITA_OITOTAL    $CHAR50.
COD_OFERTA_ACEITA_OITOTAL    $CHAR50.
COD_CAMPANHA_ACEITA_FIXO    $CHAR60.
COD_OFERTA_ACEITA_FIXO    $CHAR60.
COD_CAMPANHA_ACEITA_VELOX    $CHAR50.
COD_OFERTA_ACEITA_VELOX    $CHAR10.
COD_CAMPANHA_ACEITA_BLM    $CHAR10.
COD_OFERTA_ACEITA_BLM    $CHAR10.
COD_CAMPANHA_ACEITA_TV    $CHAR40.
COD_OFERTA_ACEITA_TV    $CHAR10.
COD_CAMPANHA_ACEITA_VOZ_MV    $CHAR50.
COD_OFERTA_ACEITA_VOZ_MV    $CHAR50.
COD_CAMPANHA_ACEITA_DADOS_MV    $CHAR10.
COD_OFERTA_ACEITA_DADOS_MV    $CHAR10.
QTE_DEPENDENTES_ANTES    BEST20.
QTE_DEPENDENTES_DEPOIS    BEST20.
FRAN_BLM_ANTES    $CHAR10.
FRAN_BLM_DEPOIS    $CHAR10.
RESULTADO_ATENDIMENTO_N10    $CHAR10.
RESULTADO_ATENDIMENTO_N11    $CHAR10.
RESULTADO_ATENDIMENTO_N12    $CHAR10.
RESULTADO_ATENDIMENTO_N13    $CHAR20.
RESULTADO_ATENDIMENTO_N14    $CHAR20.
RESULTADO_ATENDIMENTO_N20    BEST20.
RESULTADO_ATENDIMENTO_N21    BEST20.
RESULTADO_ATENDIMENTO_N22    $CHAR10.
RESULTADO_ATENDIMENTO_N23    BEST20.
RESULTADO_ATENDIMENTO_N24    BEST20.
RESULTADO_ATENDIMENTO_N25    $CHAR10.
RESULTADO_ATENDIMENTO_N26    $CHAR20.
RESULTADO_ATENDIMENTO_N27    $CHAR10.
RESULTADO_ATENDIMENTO_N29    $CHAR20.
RESULTADO_ATENDIMENTO_N30    $CHAR20.
RESULTADO_ATENDIMENTO_N31    $CHAR10.
RESULTADO_ATENDIMENTO_N32    $CHAR10.
RESULTADO_ATENDIMENTO_N33    $CHAR10.
RESULTADO_ATENDIMENTO_N34    $CHAR10.
RESULTADO_ATENDIMENTO_N35    $CHAR10.
RESULTADO_ATENDIMENTO_N36    $CHAR10.
RESULTADO_ATENDIMENTO_N37    $CHAR10.
RESULTADO_ATENDIMENTO_N38    $CHAR10.
DELTA_HIERARQUIA_VOZ_ACEITA    $CHAR10.
DELTA_HIERARQUIA_DADOS_ACEITA    BEST20.
DELTA_HIERARQUIA_BL_ACEITA    BEST20.
DELTA_HIERARQUIA_TV_ACEITA    BEST20.
COD_VERSAO_MACRO    $CHAR10.
COD_CLEANUP_ACEITA_BL    $CHAR10.
COD_AGR_ACEITA_FIXO    $CHAR10.
COD_DESCRICAO_ACEITA_FIXO    $CHAR50.
COD_CAMPANHA_VOZ_TOTAL    $CHAR10.
COD_CAMPANHA_PONTO_ADICIONAL    $CHAR40.
COD_CAMPANHA_DEGUSTACAO    $CHAR50.
COD_CAMPANHA_PACOTE_LACARTE    $CHAR30.
PRI_TOP_OF_APRESENTADA    $CHAR70.
PRI_TOP_OF_APRESENTADA_SEG_EST    $CHAR70.
PRI_TOP_OF_APRESENTADA_TER_EST    $CHAR70.
SEGUNDA_TOP_OFERTA_APRESENTADA    $CHAR70.
SEG_TOP_OF_APRESENTADA_SEG_EST    $CHAR70.
SEG_TOP_OF_APRESENTADA_TER_EST    $CHAR30.
TER_TOP_OF_APRESENTADA    $CHAR70.
TER_TOP_OF_APRESENTADA_SEG_EST    $CHAR50.
TER_TOP_OF_APRESENTADA_TER_EST    $CHAR10.
NOME_GUERRA_PRI_TOP_OF    $CHAR99.
NOME_GUERRA_PRI_TOP_OF_SEG_EST    $CHAR99.
NOME_GUERRA_PRI_TOP_OF_TER_EST    $CHAR99.
NOME_GUERRA_SEGUNDA_TOP_OFERTA    $CHAR99.
NOME_GUERRA_SEG_TOP_OF_SEG_EST    $CHAR99.
NOME_GUERRA_SEG_TOP_OF_TER_EST    $CHAR70.
NOME_GUERRA_TER_TOP_OF    $CHAR99.
NOME_GUERRA_TER_TOP_OF_SEG_EST    $CHAR99.
NOME_GUERRA_TER_TOP_OF_TER_EST    $CHAR10.
COD_PRIMEIRA_TOP_OFERTA    $CHAR50.
COD_PRI_TOP_OF_SEG_EST    $CHAR50.
COD_PRI_TOP_OF_TER_EST    $CHAR50.
COD_SEGUNDA_TOP_OFERTA    $CHAR50.
COD_SEGUNDA_TOP_OFERTA_SEG_EST    $CHAR50.
COD_SEGUNDA_TOP_OFERTA_TER_EST    $CHAR40.
COD_TERCEIRA_TOP_OFERTA    $CHAR50.
COD_TER_TOP_OF_SEG_EST    $CHAR50.
COD_TER_TOP_OF_TER_EST    $CHAR10.
NUM_ALEATORIO    COMMAX12.0
GRUPO_TESTE    $CHAR10.
DELTA_HIER_VOZ_TOP1_PRI_EST    BEST20.
DELTA_HIER_VOZ_TOP1_SEG_EST    BEST20.
DELTA_HIER_VOZ_TOP1_TER_EST    BEST20.
DELTA_HIERARQUIA_DADOS_PRI_EST    BEST20.
DELTA_HIERARQUIA_DADOS_SEG_EST    BEST20.
DELTA_HIERARQUIA_DADOS_TER_EST    BEST20.
DELTA_HIERARQUIA_BL_PRI_EST    BEST20.
DELTA_HIERARQUIA_BL_SEG_EST    BEST20.
DELTA_HIERARQUIA_BL_TER_EST    BEST20.
DELTA_HIERARQUIA_TV_PRI_EST    BEST20.
DELTA_HIERARQUIA_TV_SEG_EST    BEST20.
DELTA_HIERARQUIA_TV_TER_EST    BEST20.
OFERTA_FILTRADA_1_EST1    BEST20.
OFERTA_FILTRADA_1_EST2    BEST20.
OFERTA_FILTRADA_2_EST1    BEST20.
OFERTA_FILTRADA_2_EST2    BEST20.
CAT_OFERTA_PRI_TOP_OF_PRI_EST    $CHAR30.
CAT_OFERTA_SEG_TOP_OF_PRI_EST    $CHAR30.
CAT_OFERTA_TER_TOP_OF_PRI_EST    $CHAR30.
CAT_OFERTA_PRI_TOP_OF_SEG_EST    $CHAR30.
CAT_OFERTA_SEG_TOP_OF_SEG_EST    $CHAR30.
CAT_OFERTA_TER_TOP_OF_SEG_EST    $CHAR30.
VAL_ASS_VELOX_ANTES    COMMAX12.0
VAL_ASS_VELOX_DEPOIS    COMMAX12.0
VAL_SVA_VELOX_ANTES    COMMAX12.0
VAL_SVA_VELOX_DEPOIS    COMMAX12.0
IND_OFERTA_EMPACOTAMENTO    $CHAR10.
POSSE_CONTEUDOON_ANTES    $CHAR30.
POSSE_CONTEUDOON_DEPOIS    $CHAR10.
POSSE_CONTEUDOON_BENEF_ANTES    $CHAR70.
POSSE_CONTEUDOON_BENEF_DEPOIS    $CHAR70.
IND_PA_GRATIS    BEST20.
IND_ROBOTICS    BEST20.
        COD_QUARTA_TOP_OFERTA $CHAR1.
        NOME_PAC_PFC_DEPOIS $CHAR1.
        QUARTA_TOP_OFERTA_APRESENTADA $CHAR1.
        SEGMENTACAO_OFERTA_ACEITA $CHAR1.
        VAL_DADOS_QUARTA_TOP_OFERTA BEST1.
        VAL_FIXO_QUARTA_TOP_OFERTA BEST1.
        VAL_MV_QUARTA_TOP_OFERTA BEST1.
        VAL_OF_QUARTA_TOP_OFERTA BEST1.
        VAL_VELOX_QUARTA_TOP_OFERTA BEST1.
        VAL_VOZ_QUARTA_TOP_OFERTA BEST1.
        QTE_RECARGA_ANTES $CHAR1.
        QTE_RECARGA_DEPOIS $CHAR1.
        TOP_OFERTA_1_SEGMENTACAO $CHAR1.
        TOP_OFERTA_2_SEGMENTACAO $CHAR1.
        TOP_OFERTA_3_SEGMENTACAO $CHAR1.
        TOP_OFERTA_4_SEGMENTACAO $CHAR1.
        TOP_OFERTA_1_GASTOPROPOSTO $CHAR1.
        TOP_OFERTA_2_GASTOPROPOSTO $CHAR1.
        TOP_OFERTA_3_GASTOPROPOSTO $CHAR1.
        TOP_OFERTA_4_GASTOPROPOSTO $CHAR1.
        VAL_TV_QUARTA_TOP_OFERTA $CHAR1.
        IND_ROBOTICS_II BEST20.
        IND_DISP_FIBRA   BEST20.
        TEC_OFERTA_FXBL_ACEITA $CHAR5.
        TEC_OFERTA_TV_ACEITA $CHAR5.
        IND_FIBRA_TOP    BEST20.
        TP_TEC_FXBL_POSSE $CHAR5.
        TP_TEC_TV_POSSE  $CHAR5. ;

    INFILE "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/OIT/CSV/CHAMADAS_&MES._TITULAR_OIT.csv"
        FIRSTOBS = 2
        DELIMITER=";"
        MISSOVER DSD LRECL = 32797;

INPUT

UCID  
ID_BUNDLE  $
NUM_CPF_CNPJ  
NUM_CPF_DIGITADO_CHAMADA  $
NUM_CPF_INFORMADO  $
ID_CPF_FICTICIO  $
ID_TERMINAL  $
TP_PRODUTO_OITOTAL  $
CELULA_OPERADOR  $
NOME_GRUPO_OPERADOR  $
ID_OPERADOR  $
NOME_OPERADOR  $
LOGIN_AGENTE_CHAMADA  $
DT_CRIACAO  $
COD_UF  $
NOME_CLIENTE  $
ID_REGISTRO_CHAMADA  
TP_CHAMADA  $
COD_REGIAO  $
CLUSTER_CLIENTE  $
NUM_GRUPO_CLUSTER  
MAX_VELOC_VELOX_DISPONIVEL  
MAX_VELOC_VELOX_CONSULTADA  
TEMPO_VIG_CONTR_FIDEL_OITOTAL  
TEMPO_VIG_CONTR_FIDEL_TV  
TEMPO_VIG_CONTR_FIDEL_MV  
QTD_DIAS_ATRASO_PAG_OIT  
QTD_DIAS_ATRASO_PAG_TV  
QTD_DIAS_ATRASO_PAG_MV  
MOTIVO_LIGACAO_CATEGORIA  $
MOTIVO_LIGACAO_NOME  $
NUM_CONTRATO_TV_ASSOCIADO  
TP_CONTRATO_TV  $
NUM_TERMINAL_MV_ASSOCIADO  $
SEM_OFERTA_1  $
SEM_OFERTA_2  $
RESULTADO_DA_CHAMADA  $
DETALHE_RESULTADO_DA_CHAMADA  $
STATUS_FINAL_FIXO  $
STATUS_FINAL_BANDA_LARGA  $
STATUS_FINAL_TV  $
STATUS_FINAL_MOVEL_TITULAR  $
DETALHE_CHAMADA_IMPRODUTIVA  $
RESULTADO_ATENDIMENTO_N28  $
NUM_PRIMEIRO_CONTATO  
NUM_SEGUNDO_CONTATO  $
POSSE_DACC  $
NOVO_DACC  $
POSSE_CONTA_ONLINE  
NOVO_CONTA_ONLINE  $
EMAIL_ENVIO  $
NOME_OFERTA_ACEITA  $
NIVEL_PRECO_OFERTA_ACEITA  $
IND_FIDELIDADE_OFERTA  
CATEGORIA_OFERTA  $
CATEGORIA_RV_OFERTA  
STATUS_ULTIMA_OFERTA  $
ARPU_OITOTAL_ANTES  
ARPU_OITOTAL_DEPOIS  
ARPU_TARGET  
ARPU_LIGACAO  
ARPU_RECEITA_ANTES  
ARPU_RECEITA_DEPOIS  
ARPU_FIXO_ANTES  
ARPU_FIXO_DEPOIS  
ARPU_RECARGA_ANTES  
ARPU_RECARGA_DEPOIS  
ARPU_VELOX_ANTES  
ARPU_VELOX_DEPOIS  
ARPU_TV_ANTES  
ARPU_TV_DEPOIS  
ARPU_MV_ANTES  
ARPU_MV_DEPOIS  
NOME_PAC_FIXO_ANTES  $
NOME_PAC_FIXO_DEPOIS  $
NOME_PAC_FIXO_LD_ANTES  $
NOME_PAC_FIXO_LD_DEPOIS  $
NOME_PAC_FIXO_VC_ANTES  $
NOME_PAC_FIXO_VC_DEPOIS  $
NOME_PAC_FIXO_SD_ANTES  $
NOME_PAC_FIXO_SD_DEPOIS  $
QTE_RECARGA_AUTO_01  
QTE_RECARGA_AUTO_10  
QTE_RECARGA_AUTO_15  
QTE_RECARGA_AUTO_20  
QTE_RECARGA_AUTO_01_DEPOIS  
QTE_RECARGA_AUTO_10_DEPOIS  
QTE_RECARGA_AUTO_15_DEPOIS  
QTE_RECARGA_AUTO_20_DEPOIS  
VAL_ASS_FIXO_ANTES  
VAL_ASS_FIXO_DEPOIS  
VAL_ASS_FIXO_SD_ANTES  
VAL_ASS_FIXO_SD_DEPOIS  
VAL_ASS_FIXO_LD_ANTES  
VAL_ASS_FIXO_LD_DEPOIS  
VAL_ASS_FIXO_VC_ANTES  
VAL_ASS_FIXO_VC_DEPOIS  
VAL_EXC_FIXO_LOC_FF_ANTES  
VAL_EXC_FIXO_LOC_FM_ANTES  
VAL_EXC_FIXO_LOC_FMOUT_ANTES  
VAL_EXC_FIXO_LD_31_ANTES  
VAL_RECARGA_PRI_TOP_OF  
VAL_RECARGA_PRI_TOP_OF_SEG_EST  
VAL_RECARGA_PRI_TOP_OF_TER_EST  
VAL_RECARGA_SEGUNDA_TOP_OFERTA  
VAL_RECARGA_SEG_TOP_OF_SEG_EST  
VAL_RECARGA_SEG_TOP_OF_TER_EST  
VAL_RECARGA_TER_TOP_OF  
VAL_RECARGA_TER_TOP_OF_SEG_EST  
VAL_RECARGA_TER_TOP_OF_TER_EST  
VAL_FIXO_PRIMEIRA_TOP_OFERTA  
VAL_FIXO_PRI_TOP_OF_SEG_EST  
VAL_FIXO_PRI_TOP_OF_TER_EST  
VAL_FIXO_SEGUNDA_TOP_OFERTA  
VAL_FIXO_SEG_TOP_OF_SEG_EST  
VAL_FIXO_SEG_TOP_OF_TER_EST  
VAL_FIXO_TERCEIRA_TOP_OFERTA  
VAL_FIXO_TER_TOP_OF_SEG_EST  
VAL_FIXO_TER_TOP_OF_TER_EST  
VAL_TAD_FIXO  
NOME_PAC_VELOX_ANTES  $
NOME_PAC_VELOX_DEPOIS  $
NOME_PAC_BLM_ANTES  $
NOME_PAC_BLM_DEPOIS  $
VELOC_VELOX_OFERTA_ACEITA  $
VAL_VELOX_PRIMEIRA_TOP_OFERTA  
VAL_VELOX_PRI_TOP_OF_SEG_EST  
VAL_VELOX_PRI_TOP_OF_TER_EST  
VAL_VELOX_SEGUNDA_TOP_OFERTA  
VAL_VELOX_SEG_TOP_OF_SEG_EST  
VAL_VELOX_SEG_TOP_OF_TER_EST  
VAL_VELOX_TERCEIRA_TOP_OFERTA  
VAL_VELOX_TER_TOP_OF_SEG_EST  
VAL_VELOX_TER_TOP_OF_TER_EST  
VAL_THAB_VELOX  
IND_POSSE_COMBATE  
IND_POSSE_ETNICO  
IND_POSSE_PFC  
IND_POSSE_PLAYBOY  
IND_POSSE_PLAYBOY_SEXYHOT  
IND_POSSE_PRIVE  
IND_POSSE_SEXYHOT  
IND_POSSE_COMBATE_DEPOIS  
IND_POSSE_ETNICO_DEPOIS  
IND_POSSE_PFC_DEPOIS  
IND_POSSE_PLAYBOY_DEPOIS  
IND_POSSE_PRIVE_DEPOIS  
IND_POSSE_SEXYHOT_DEPOIS  
IND_POSSE_BBB_DEPOIS  
IND_POSSE_PLAYBOYSEXHOT_DEPOIS  
IND_POSSE_CONTEUDOON_ANTES  
IND_POSSE_CONTEUDOON_DEPOIS  $
IND_POSSE_DVR_ANTES  
IND_POSSE_DVR_DEPOIS  
IND_POSSE_PENVR_ANTES  
IND_POSSE_PENVR_DEPOIS  
QTD_PONTOS_ADIC_TV_ANTES  
QTD_PONTOS_ADIC_TV_DEPOIS  
TP_SATELITE_ANTES  $
TP_SATELITE_DEPOIS  $
NOME_PAC_TV_ANTES  $
NOME_PAC_TV_DEPOIS  $
NOME_DEGUSTACAO_TV_DEPOIS  $
PERIODO_DEGUSTACAO_TV_DEPOIS  
VAL_PLANO_TV_ANTES  
VAL_PLANO_TV_DEPOIS  
VAL_LA_CARTE_ANTES  
VAL_LA_CARTE_DEPOIS  
VAL_PONTOS_ADIC_ANTES  
VAL_PONTOS_ADIC_DEPOIS  
VAL_PENVR_ANTES  
VAL_PENVR_DEPOIS  
VAL_TV_PRIMEIRA_TOP_OFERTA  
VAL_TV_PRI_TOP_OF_SEG_EST  
VAL_TV_PRI_TOP_OF_TER_EST  
VAL_TV_SEGUNDA_TOP_OFERTA  
VAL_TV_SEG_TOP_OF_SEG_EST  
VAL_TV_SEG_TOP_OF_TER_EST  
VAL_TV_TERCEIRA_TOP_OFERTA  
VAL_TV_TER_TOP_OF_SEG_EST  
VAL_TV_TER_TOP_OF_TER_EST  
VAL_THAB_TV  
NOME_PAC_MV_VOZ_ANTES  $
NOME_PAC_MV_VOZ_DEPOIS  $
NOME_PAC_MV_DADOS_TIT_ANTES  $
NOME_PAC_MV_DADOS_TIT_DEPOIS  $
NOME_PAC_MV_LD_ANTES  $
NOME_PAC_MV_LD_DEPOIS  $
VAL_ASS_MV_VOZ_ANTES  
VAL_ASS_MV_VOZ_DEPOIS  
VAL_ASS_MV_DADOS_TIT_ANTES  
VAL_ASS_MV_DADOS_TIT_DEPOIS  
VAL_ASS_MV_LD_ANTES  
VAL_ASS_MV_LD_DEPOIS  
VAL_ASS_MV_DADOS_DEP_ANTES  
VAL_ASS_MV_DADOS_DEP_DEPOIS  
VAL_ASS_MV_DEP_ANTES  
VAL_ASS_MV_DEP_DEPOIS  
VAL_EXC_LD_ON_MV_OI_ANTES  
VAL_EXC_LD_OFF_MV_OI_ANTES  
VAL_EXC_LD_ON_MV_OUT_ANTES  
VAL_EXC_LD_OFF_MV_OUT_ANTES  
VAL_EXC_LOCAL_ON_MV_ANTES  
VAL_EXC_LOCAL_OFF_MV_ANTES  
VAL_EXC_SMS_MV_ANTES  
VAL_EXC_DADOS_MV_ANTES  
VAL_EXC_OUTROS_MV_ANTES  
VAL_VOZ_PRIMEIRA_TOP_OFERTA  
VAL_VOZ_PRI_TOP_OF_SEG_EST  
VAL_VOZ_PRI_TOP_OF_TER_EST  
VAL_DADOS_PRIMEIRA_TOP_OFERTA  
VAL_DADOS_PRI_TOP_OF_SEG_EST  
VAL_DADOS_PRI_TOP_OF_TER_EST  
VAL_MOVEL_PRIMEIRA_TOP_OFERTA  
VAL_MOVEL_PRI_TOP_OF_SEG_EST  
VAL_MOVEL_PRI_TOP_OF_TER_EST  
VAL_VOZ_SEGUNDA_TOP_OFERTA  
VAL_VOZ_SEG_TOP_OF_SEG_EST  
VAL_VOZ_SEG_TOP_OF_TER_EST  
VAL_DADOS_SEGUNDA_TOP_OFERTA  
VAL_DADOS_SEG_TOP_OF_SEG_EST  
VAL_DADOS_SEG_TOP_OF_TER_EST  
VAL_MOVEL_SEGUNDA_TOP_OFERTA  
VAL_MOVEL_SEG_TOP_OF_SEG_EST  
VAL_MOVEL_SEG_TOP_OF_TER_EST  
VAL_VOZ_TERCEIRA_TOP_OFERTA  
VAL_VOZ_TER_TOP_OF_SEG_EST  
VAL_VOZ_TER_TOP_OF_TER_EST  
VAL_DADOS_TERCEIRA_TOP_OFERTA  
VAL_DADOS_TER_TOP_OF_SEG_EST  
VAL_DADOS_TER_TOP_OF_TER_EST  
VAL_MOVEL_TERCEIRA_TOP_OFERTA  
VAL_MOVEL_TER_TOP_OF_SEG_EST  
VAL_MOVEL_TER_TOP_OF_TER_EST  
VAL_OFERTA_PRIMEIRA_TOP_OFERTA  
VAL_OF_PRI_TOP_OF_SEG_EST  
VAL_OF_PRI_TOP_OF_TER_EST  
VAL_OFERTA_SEGUNDA_TOP_OFERTA  
VAL_OF_SEG_TOP_OF_SEG_EST  
VAL_OF_SEG_TOP_OF_TER_EST  
VAL_OFERTA_TERCEIRA_TOP_OFERTA  
VAL_OF_TER_TOP_OF_SEG_EST  
VAL_OF_TER_TOP_OF_TER_EST  
COD_PLANO_ACEITA_OITOTAL  $
COD_CAMPANHA_ACEITA_OITOTAL  $
COD_OFERTA_ACEITA_OITOTAL  $
COD_CAMPANHA_ACEITA_FIXO  $
COD_OFERTA_ACEITA_FIXO  $
COD_CAMPANHA_ACEITA_VELOX  $
COD_OFERTA_ACEITA_VELOX  $
COD_CAMPANHA_ACEITA_BLM  $
COD_OFERTA_ACEITA_BLM  $
COD_CAMPANHA_ACEITA_TV  $
COD_OFERTA_ACEITA_TV  $
COD_CAMPANHA_ACEITA_VOZ_MV  $
COD_OFERTA_ACEITA_VOZ_MV  $
COD_CAMPANHA_ACEITA_DADOS_MV  $
COD_OFERTA_ACEITA_DADOS_MV  $
QTE_DEPENDENTES_ANTES  
QTE_DEPENDENTES_DEPOIS  
FRAN_BLM_ANTES  $
FRAN_BLM_DEPOIS  $
RESULTADO_ATENDIMENTO_N10  $
RESULTADO_ATENDIMENTO_N11  $
RESULTADO_ATENDIMENTO_N12  $
RESULTADO_ATENDIMENTO_N13  $
RESULTADO_ATENDIMENTO_N14  $
RESULTADO_ATENDIMENTO_N20  
RESULTADO_ATENDIMENTO_N21  
RESULTADO_ATENDIMENTO_N22  $
RESULTADO_ATENDIMENTO_N23  
RESULTADO_ATENDIMENTO_N24  
RESULTADO_ATENDIMENTO_N25  $
RESULTADO_ATENDIMENTO_N26  $
RESULTADO_ATENDIMENTO_N27  $
RESULTADO_ATENDIMENTO_N29  $
RESULTADO_ATENDIMENTO_N30  $
RESULTADO_ATENDIMENTO_N31  $
RESULTADO_ATENDIMENTO_N32  $
RESULTADO_ATENDIMENTO_N33  $
RESULTADO_ATENDIMENTO_N34  $
RESULTADO_ATENDIMENTO_N35  $
RESULTADO_ATENDIMENTO_N36  $
RESULTADO_ATENDIMENTO_N37  $
RESULTADO_ATENDIMENTO_N38  $
DELTA_HIERARQUIA_VOZ_ACEITA  $
DELTA_HIERARQUIA_DADOS_ACEITA  
DELTA_HIERARQUIA_BL_ACEITA  
DELTA_HIERARQUIA_TV_ACEITA  
COD_VERSAO_MACRO  $
COD_CLEANUP_ACEITA_BL  $
COD_AGR_ACEITA_FIXO  $
COD_DESCRICAO_ACEITA_FIXO  $
COD_CAMPANHA_VOZ_TOTAL  $
COD_CAMPANHA_PONTO_ADICIONAL  $
COD_CAMPANHA_DEGUSTACAO  $
COD_CAMPANHA_PACOTE_LACARTE  $
PRI_TOP_OF_APRESENTADA  $
PRI_TOP_OF_APRESENTADA_SEG_EST  $
PRI_TOP_OF_APRESENTADA_TER_EST  $
SEGUNDA_TOP_OFERTA_APRESENTADA  $
SEG_TOP_OF_APRESENTADA_SEG_EST  $
SEG_TOP_OF_APRESENTADA_TER_EST  $
TER_TOP_OF_APRESENTADA  $
TER_TOP_OF_APRESENTADA_SEG_EST  $
TER_TOP_OF_APRESENTADA_TER_EST  $
NOME_GUERRA_PRI_TOP_OF  $
NOME_GUERRA_PRI_TOP_OF_SEG_EST  $
NOME_GUERRA_PRI_TOP_OF_TER_EST  $
NOME_GUERRA_SEGUNDA_TOP_OFERTA  $
NOME_GUERRA_SEG_TOP_OF_SEG_EST  $
NOME_GUERRA_SEG_TOP_OF_TER_EST  $
NOME_GUERRA_TER_TOP_OF  $
NOME_GUERRA_TER_TOP_OF_SEG_EST  $
NOME_GUERRA_TER_TOP_OF_TER_EST  $
COD_PRIMEIRA_TOP_OFERTA  $
COD_PRI_TOP_OF_SEG_EST  $
COD_PRI_TOP_OF_TER_EST  $
COD_SEGUNDA_TOP_OFERTA  $
COD_SEGUNDA_TOP_OFERTA_SEG_EST  $
COD_SEGUNDA_TOP_OFERTA_TER_EST  $
COD_TERCEIRA_TOP_OFERTA  $
COD_TER_TOP_OF_SEG_EST  $
COD_TER_TOP_OF_TER_EST  $
NUM_ALEATORIO  
GRUPO_TESTE  $
DELTA_HIER_VOZ_TOP1_PRI_EST  
DELTA_HIER_VOZ_TOP1_SEG_EST  
DELTA_HIER_VOZ_TOP1_TER_EST  
DELTA_HIERARQUIA_DADOS_PRI_EST  
DELTA_HIERARQUIA_DADOS_SEG_EST  
DELTA_HIERARQUIA_DADOS_TER_EST  
DELTA_HIERARQUIA_BL_PRI_EST  
DELTA_HIERARQUIA_BL_SEG_EST  
DELTA_HIERARQUIA_BL_TER_EST  
DELTA_HIERARQUIA_TV_PRI_EST  
DELTA_HIERARQUIA_TV_SEG_EST  
DELTA_HIERARQUIA_TV_TER_EST  
OFERTA_FILTRADA_1_EST1  
OFERTA_FILTRADA_1_EST2  
OFERTA_FILTRADA_2_EST1  
OFERTA_FILTRADA_2_EST2  
CAT_OFERTA_PRI_TOP_OF_PRI_EST  $
CAT_OFERTA_SEG_TOP_OF_PRI_EST  $
CAT_OFERTA_TER_TOP_OF_PRI_EST  $
CAT_OFERTA_PRI_TOP_OF_SEG_EST  $
CAT_OFERTA_SEG_TOP_OF_SEG_EST  $
CAT_OFERTA_TER_TOP_OF_SEG_EST  $
VAL_ASS_VELOX_ANTES  
VAL_ASS_VELOX_DEPOIS  
VAL_SVA_VELOX_ANTES  
VAL_SVA_VELOX_DEPOIS  
IND_OFERTA_EMPACOTAMENTO  $
POSSE_CONTEUDOON_ANTES  $
POSSE_CONTEUDOON_DEPOIS  $
POSSE_CONTEUDOON_BENEF_ANTES  $
POSSE_CONTEUDOON_BENEF_DEPOIS  $
IND_PA_GRATIS  
IND_ROBOTICS
COD_QUARTA_TOP_OFERTA $
NOME_PAC_PFC_DEPOIS $
QUARTA_TOP_OFERTA_APRESENTADA $
SEGMENTACAO_OFERTA_ACEITA $
VAL_DADOS_QUARTA_TOP_OFERTA
VAL_FIXO_QUARTA_TOP_OFERTA
VAL_MV_QUARTA_TOP_OFERTA
VAL_OF_QUARTA_TOP_OFERTA
VAL_VELOX_QUARTA_TOP_OFERTA
VAL_VOZ_QUARTA_TOP_OFERTA
QTE_RECARGA_ANTES $
QTE_RECARGA_DEPOIS $
TOP_OFERTA_1_SEGMENTACAO $
TOP_OFERTA_2_SEGMENTACAO $
TOP_OFERTA_3_SEGMENTACAO $
TOP_OFERTA_4_SEGMENTACAO $
TOP_OFERTA_1_GASTOPROPOSTO $
TOP_OFERTA_2_GASTOPROPOSTO $
TOP_OFERTA_3_GASTOPROPOSTO $
TOP_OFERTA_4_GASTOPROPOSTO $
VAL_TV_QUARTA_TOP_OFERTA $
IND_ROBOTICS_II
IND_DISP_FIBRA
TEC_OFERTA_FXBL_ACEITA $
TEC_OFERTA_TV_ACEITA $
IND_FIBRA_TOP
TP_TEC_FXBL_POSSE $
TP_TEC_TV_POSSE $;

/*IF TP_CHAMADA="Produtiva";*/ ANOMES =&MES.; /* <-- Remove improdutivas e cria o anomes */

/* Separa data e hora --> */
DT_LIGACAO= MDY(SUBSTR(DT_CRIACAO, 4, 2), SUBSTR(DT_CRIACAO, 1, 2), SUBSTR(DT_CRIACAO, 7, 4));
HORARIO_LIGACAO = INPUT(SUBSTR(DT_CRIACAO, 12, 2) !! ':' !! SUBSTR(DT_CRIACAO, 15, 2) !! ':' !! SUBSTR(DT_CRIACAO, 18, 2), TIME8.);

/* Remove DDD duplicado nos casos que ocorrem --> */
IF LENGTH(ID_TERMINAL)>10 THEN DDD_TELEFONE=SUBSTRN(ID_TERMINAL, 3, 12); ELSE DDD_TELEFONE=ID_TERMINAL;

/* Classifica o tipo de CPF em uma única coluna --> */
IF CMISS(NUM_CPF_CNPJ, ID_CPF_FICTICIO)=2 THEN CPF_FLAG=""; ELSE 
IF MISSING(ID_CPF_FICTICIO) THEN CPF_FLAG="NÃO FICTICIO";ELSE CPF_FLAG="FICTICIO";

/* Valida o ID_BUNDLE dos fictícios --> */
IF CPF_FLAG IN ("","FICTICIO") THEN DO;VAL_ID_BUNDLE="INVALIDO";
	IF ANYALPHA(ID_BUNDLE) NOT=0 THEN DO;
		IF ANYDIGIT(ID_BUNDLE) NOT=0 THEN DO;
			IF LENGTH(ID_BUNDLE) IN (8, 9, 10) THEN DO;
				IF SUBSTR(ID_BUNDLE, 1, 2) NOT="1-" THEN DO;
					IF SUBSTR(ID_BUNDLE, 1, 1) IN ("1", "-") THEN DO;
						ID_BUNDLE=UPCASE(CATS("1-",SUBSTR(ID_BUNDLE, 2,LENGTH(ID_BUNDLE))));END;END;
				IF SUBSTR(ID_BUNDLE, 1, 2)="1-" THEN DO; 
				VAL_ID_BUNDLE="VALIDO";END;END;END;END;END;

IF CPF_FLAG="NÃO FICTICIO" THEN VAL_ID_BUNDLE ="VALIDO";

/* Cria o delta hierarquia total da oferta aceita pelo cliente --> */
DELTA_HIER_OFERTA_ACEITA=SUM(DELTA_HIERARQUIA_VOZ_ACEITA, DELTA_HIERARQUIA_DADOS_ACEITA, DELTA_HIERARQUIA_BL_ACEITA, DELTA_HIERARQUIA_TV_ACEITA); 

/* Reescreve o bundle inicial --> */
IF TP_PRODUTO_OITOTAL="Fixo" THEN TP_PRODUTO_OITOTAL="1P FX";
IF TP_PRODUTO_OITOTAL="Oi Total Fixo" THEN TP_PRODUTO_OITOTAL="1P FX";
IF TP_PRODUTO_OITOTAL="FixoVelox" THEN TP_PRODUTO_OITOTAL="2P BL";
IF TP_PRODUTO_OITOTAL="FixoTV" THEN TP_PRODUTO_OITOTAL="2P TV";
IF TP_PRODUTO_OITOTAL="FixoVeloxTV" THEN TP_PRODUTO_OITOTAL="3P RES";
IF TP_PRODUTO_OITOTAL="FixoVeloxMovel" THEN TP_PRODUTO_OITOTAL="3P MOVEL";
IF TP_PRODUTO_OITOTAL="FixoVeloxMovelTV" THEN TP_PRODUTO_OITOTAL="4P";

/* Reescreve o resultado da chamada --> */
IF DETALHE_RESULTADO_DA_CHAMADA="Retido com Argumentação / Ação" THEN RESULTADO="RETIDO_ARG";ELSE
IF DETALHE_RESULTADO_DA_CHAMADA="Cancelado - Manteve um ou mais produtos fora do combo" THEN RESULTADO="CANCELADO_ALONE";ELSE
IF DETALHE_RESULTADO_DA_CHAMADA="Cancelado - Não manteve nenhum produto fora do combo" THEN RESULTADO="CANCELADO";ELSE
IF DETALHE_RESULTADO_DA_CHAMADA="Retido com Oferta - Com Retirada" THEN RESULTADO="OFERTA_DOWN";ELSE
IF DETALHE_RESULTADO_DA_CHAMADA="Retido com Oferta - Com Inclusão e Retirada" THEN RESULTADO="OFERTA_RET_INC";ELSE
IF DETALHE_RESULTADO_DA_CHAMADA="Retido com Oferta - Mesmo Combo" THEN RESULTADO="OFERTA_LATERAL";ELSE
IF DETALHE_RESULTADO_DA_CHAMADA="Retido com Oferta - Com Inclusão" THEN RESULTADO="OFERTA_UP";ELSE RESULTADO="OUTROS";

STATUS_FX_BL_TV_MV=CATX(" | ", STATUS_FINAL_FIXO, STATUS_FINAL_BANDA_LARGA, STATUS_FINAL_TV, STATUS_FINAL_MOVEL_TITULAR);

/* Escreve o bundle final --> */
ARRAY STATUS{2,4} STATUS_FINAL_FIXO STATUS_FINAL_BANDA_LARGA STATUS_FINAL_TV STATUS_FINAL_MOVEL_TITULAR DETALHE_STATUS_FINAL_FIXO DETALHE_STATUS_FINAL_BL DETALHE_STATUS_FINAL_TV DETALHE_STATUS_FINAL_MV;
DO i= 1 to 4;
IF STATUS{1,i} IN ("Dentro do combo - Mantido", "Dentro do combo - Aquisição", "Dentro do combo - Associação") THEN UGR_BUNDLE=CATS(i,UGR_BUNDLE);
END;

IF UGR_BUNDLE=1 THEN BUNDLE_FINAL="1P FX";
IF UGR_BUNDLE=21 THEN BUNDLE_FINAL="2P BL";
IF UGR_BUNDLE=31 THEN BUNDLE_FINAL="2P TV";
IF UGR_BUNDLE=321 THEN BUNDLE_FINAL="3P RES";
IF UGR_BUNDLE=421 THEN BUNDLE_FINAL="3P MOVEL";
IF UGR_BUNDLE=4321 THEN BUNDLE_FINAL="4P";
RUN;

PROC SQL;
	CREATE TABLE FATURADO AS /* <-- Cruza com o faturado e com a base da ilha de downgrade */
	SELECT A.*,

			/* Ticket antes --> */
			C.FAT_FX_RECORR FORMAT=COMMAX8.2 AS TICKET_ANTES_FX,
			C.FAT_BL_RECORR FORMAT=COMMAX8.2 AS TICKET_ANTES_BL,
		SUM(C.VLR_BRTO_ASS_MOVEL, 
			C.VLR_BRTO_FRANQUIA_MÓVEL) FORMAT=COMMAX8.2 AS TICKET_ANTES_MV_VOZ,
		SUM(C.VLR_BRTO_ASS_DADOS_3G, 
			C.VLR_BRTO_SVA_MOVEL_3G) FORMAT=COMMAX8.2 AS TICKET_ANTES_MV_DADOS,
		SUM(C.FAT_TV, 
			C.FAT_TV_ALC, 
			C.FAT_TV_PA) FORMAT=COMMAX8.2 AS TICKET_ANTES_TV,
		SUM(C.VLR_BRTO_ASS_MOVEL, 
			C.VLR_BRTO_FRANQUIA_MÓVEL, 
			C.VLR_BRTO_ASS_DADOS_3G, 
			C.VLR_BRTO_SVA_MOVEL_3G) FORMAT=COMMAX8.2 AS TICKET_ANTES_MV,
	CASE 
		WHEN A.TP_PRODUTO_OITOTAL EQ "1P FX" THEN
			C.FAT_FX_RECORR

		WHEN A.TP_PRODUTO_OITOTAL EQ "2P BL" THEN
			SUM(C.FAT_FX_RECORR,
				C.FAT_BL_RECORR)

		WHEN A.TP_PRODUTO_OITOTAL EQ "2P TV" THEN
			SUM(C.FAT_FX_RECORR,
				C.FAT_TV, 
				C.FAT_TV_ALC, 
				C.FAT_TV_PA)

		WHEN A.TP_PRODUTO_OITOTAL EQ "3P RES" THEN	
			SUM(C.FAT_FX_RECORR,
				C.FAT_BL_RECORR,
				C.FAT_TV, 
				C.FAT_TV_ALC, 
				C.FAT_TV_PA)

		WHEN A.TP_PRODUTO_OITOTAL EQ "3P MOVEL" THEN
			SUM(C.FAT_FX_RECORR,
				C.FAT_BL_RECORR,
				C.VLR_BRTO_ASS_MOVEL, 
				C.VLR_BRTO_FRANQUIA_MÓVEL,
				C.VLR_BRTO_ASS_DADOS_3G, 
				C.VLR_BRTO_SVA_MOVEL_3G)

		WHEN A.TP_PRODUTO_OITOTAL EQ "4P" THEN
			SUM(C.FAT_FX_RECORR,
				C.FAT_BL_RECORR,
				C.FAT_TV, 
				C.FAT_TV_ALC, 
				C.FAT_TV_PA,
				C.VLR_BRTO_ASS_MOVEL, 
				C.VLR_BRTO_FRANQUIA_MÓVEL,
				C.VLR_BRTO_ASS_DADOS_3G, 
				C.VLR_BRTO_SVA_MOVEL_3G) END FORMAT=COMMAX8.2 AS TICKET_ANTES_OIT,

			C.FAT_TOTAL AS TICKET_ANTES_RECEITA,

			/* Ticket depois --> */
			 A.ARPU_FIXO_DEPOIS AS TICKET_DEPOIS_FX,
			 A.ARPU_VELOX_DEPOIS AS TICKET_DEPOIS_BL,
			 A.ARPU_TV_DEPOIS AS TICKET_DEPOIS_TV,
		 SUM(A.VAL_ASS_MV_VOZ_DEPOIS, 
			 A.VAL_ASS_MV_LD_DEPOIS) AS TICKET_DEPOIS_MV_VOZ,
			 A.VAL_ASS_MV_DADOS_TIT_DEPOIS AS TICKET_DEPOIS_MV_DADOS,
			 A.ARPU_MV_DEPOIS AS TICKET_DEPOIS_MV,
	CASE 
		WHEN A.BUNDLE_FINAL EQ "1P FX" THEN
			TICKET_DEPOIS_FX

		WHEN A.BUNDLE_FINAL EQ "2P BL" THEN
			SUM(TICKET_DEPOIS_FX,
				TICKET_DEPOIS_BL)

		WHEN A.BUNDLE_FINAL EQ "2P TV" THEN
			SUM(TICKET_DEPOIS_FX,
				TICKET_DEPOIS_TV)

		WHEN A.BUNDLE_FINAL EQ "3P RES" THEN
			SUM(TICKET_DEPOIS_FX,
				TICKET_DEPOIS_BL,
				TICKET_DEPOIS_TV)

		WHEN A.BUNDLE_FINAL EQ "3P MOVEL" THEN
			SUM(TICKET_DEPOIS_FX,
				TICKET_DEPOIS_BL,
				TICKET_DEPOIS_MV)

		WHEN A.BUNDLE_FINAL EQ "4P" THEN
			SUM(TICKET_DEPOIS_FX,
				TICKET_DEPOIS_BL,
				TICKET_DEPOIS_TV,
				TICKET_DEPOIS_MV) END FORMAT=COMMAX8.2 AS TICKET_DEPOIS_OIT,

			A.ARPU_RECEITA_DEPOIS AS TICKET_DEPOIS_RECEITA,
			
			/* Exc. fixo, móvel e minutos --> */
			C.FAT_FX_EXCED, 
			C.FAT_MV_EXCED,
			C.FAT_EXCED_TOTAL,
			C.MIN_LDN_FF,
			C.MIN_LDN_FM,
			C.MIN_LD_FM_ON,
			C.MIN_LDN_FM_OFF,
			C.MIN_VC1,
			C.MIN_VC1_ON,
			C.MIN_VC1_OFF,
			C.MIN_LOCAL_MM,
			C.MIN_LOCAL_MM_ON,
			C.MIN_LOCAL_MM_OFF,
			C.MIN_LD_MM,
			C.MIN_LD_MM_ON,
			C.MIN_LD_MM_OFF,
			C.MIN_LOCAL_MF,
			C.MIN_LD_MF,
			/*D.AGING_BUNDLE,*/

		CASE WHEN A.ID_OPERADOR=B.ID_OPERADOR AND A.DT_LIGACAO>=B.DATA_INICIO AND (A.DT_LIGACAO<B.DATA_FIM OR B.DATA_FIM=.)  THEN 1 ELSE . END AS ILHA_DOWNGRADE,
		CASE WHEN A.TP_PRODUTO_OITOTAL EQ F.TP_PRODUTO_OITOTAL AND A.STATUS_FX_BL_TV_MV EQ F.STATUS_FX_BL_TV_MV THEN F.RESULTADO END AS RESULTADO_NEW,
		CASE WHEN (A.STATUS_FX_BL_TV_MV EQ E.STATUS_FX_BL_TV_MV AND A.RESULTADO EQ E.RESULTADO AND A.TP_PRODUTO_OITOTAL EQ E.TP_PRODUTO_OITOTAL) THEN 0 ELSE 1 END AS FLAG_STATUS

	FROM CHAMADAS_&MES._TITULAR_OIT_FB AS A
			LEFT JOIN OIT.ILHA_DOWNGRADE AS B ON A.ID_OPERADOR=B.ID_OPERADOR
			LEFT JOIN FAT_SUM.FAT_OIT_SUM_&NMES. AS C ON A.DDD_TELEFONE > 2100000000 AND A.DDD_TELEFONE= C.DDD_TELEFONE
			/*LEFT JOIN PLANTA_OIT_&NMES. AS D ON A.DDD_TELEFONE= D.DDD_TELEFONE*/
			LEFT JOIN OIT.RESULTADO_STATUS_OIT E ON A.TP_PRODUTO_OITOTAL EQ E.TP_PRODUTO_OITOTAL AND A.STATUS_FX_BL_TV_MV EQ E.STATUS_FX_BL_TV_MV AND A.RESULTADO EQ E.RESULTADO
			LEFT JOIN OIT.RESULTADO_STATUS_OIT F ON A.TP_PRODUTO_OITOTAL EQ F.TP_PRODUTO_OITOTAL AND A.STATUS_FX_BL_TV_MV EQ F.STATUS_FX_BL_TV_MV AND F.RESULTADO NE "OFERTA_LATERAL" AND F.RESULTADO NE "RETIDO_ARG";
QUIT;

DATA OIT.CHAMADAS_&MES._TITULAR_OIT_FB;
SET FATURADO;

IF FLAG_STATUS=1 AND RESULTADO_NEW NOT="" THEN DO;
	RESULTADO=RESULTADO_NEW;
	FLAG_STATUS=0;
END;

ARRAY BUNDLE{2} TP_PRODUTO_OITOTAL BUNDLE_FINAL;
ARRAY STATUS{2,4} STATUS_FINAL_FIXO STATUS_FINAL_BANDA_LARGA STATUS_FINAL_TV STATUS_FINAL_MOVEL_TITULAR DETALHE_STATUS_FINAL_FIXO DETALHE_STATUS_FINAL_BL DETALHE_STATUS_FINAL_TV DETALHE_STATUS_FINAL_MV;
ARRAY ARPU{3,4} ARPU_FIXO_ANTES ARPU_VELOX_ANTES ARPU_TV_ANTES ARPU_MV_ANTES ARPU_FIXO_DEPOIS ARPU_VELOX_DEPOIS ARPU_TV_DEPOIS ARPU_MV_DEPOIS DELTA_ARPU_FX DELTA_ARPU_BL DELTA_ARPU_TV DELTA_ARPU_MV;
ARRAY TICKET{3,4} TICKET_ANTES_FX TICKET_ANTES_BL TICKET_ANTES_TV TICKET_ANTES_MV TICKET_DEPOIS_FX TICKET_DEPOIS_BL TICKET_DEPOIS_TV TICKET_DEPOIS_MV DELTA_TICKET_FX DELTA_TICKET_BL DELTA_TICKET_TV DELTA_TICKET_MV;
ARRAY ARPU_OIT{3,4} ARPU_OITOTAL_ANTES ARPU_RECEITA_ANTES TICKET_ANTES_OIT TICKET_ANTES_RECEITA ARPU_OITOTAL_DEPOIS ARPU_RECEITA_DEPOIS TICKET_DEPOIS_OIT TICKET_DEPOIS_RECEITA DELTA_ARPU_OIT DELTA_ARPU_RECEITA DELTA_TICKET_OIT DELTA_TICKET_RECEITA;
ARRAY NOME_PAC{7,2} NOME_PAC_FIXO_LD_ANTES NOME_PAC_FIXO_LD_DEPOIS NOME_PAC_FIXO_VC_ANTES NOME_PAC_FIXO_VC_DEPOIS PACOTE_FIXO_ANTES PACOTE_FIXO_DEPOIS NOME_PAC_VELOX_ANTES NOME_PAC_VELOX_DEPOIS NOME_PAC_TV_ANTES NOME_PAC_TV_DEPOIS NOME_PAC_MV_DADOS_TIT_ANTES NOME_PAC_MV_DADOS_TIT_DEPOIS NOME_PAC_MV_VOZ_ANTES NOME_PAC_MV_VOZ_DEPOIS;

MANTIDO=0;CANCELADO=0;ALONE=0;AQUISICAO=0;FLAG_ARPU=0;FLAG_TICKET=0;

DO k=1 to 2;DO i=1 to 4;

IF ARPU{k,i}=. THEN ARPU{k,i}=0;
IF TICKET{k,i}=. THEN TICKET{k,i}=0;
IF ARPU_OIT{k,i}=. THEN ARPU_OIT{k,i}=0;END;END;

DO i= 1 to 4;

	/* Detalha o resultado da chamada para cada UGR --> */
	IF STATUS{1,i} IN("Dentro do combo - Mantido") THEN DO;
		MANTIDO=MANTIDO+1;

		IF RESULTADO IN ("OFERTA_LATERAL", "OFERTA_DOWN", "OFERTA_RET_INC", "OFERTA_UP") THEN DO;
			STATUS{2,i}="Retido - Oferta Dentro do OIT";END;

		IF RESULTADO IN ("RETIDO_ARG") THEN DO;
			STATUS{2,i}="Retido - Argumentação";
			TICKET{2,i}=TICKET{1,i}; /* <-- Inf. de ARPU depois e antes igual para os Ret. Argumentação */
			ARPU{2,i}=ARPU{1,i};END;END;

	IF STATUS{1,i} IN("Dentro do combo - Aquisição") THEN DO;
		AQUISICAO=AQUISICAO+1;
		STATUS{2,i}="Retido - Aquisição da UGR";
		TICKET{1,i}=0; /* <-- Inf. de ARPU ANTES igual a zero para os adquiridos */
		ARPU{1,i}=0;END;

	IF STATUS{1,i} IN("Cancelado" "Migrado para Pré") THEN DO;
		CANCELADO=CANCELADO+1;
		STATUS{2,i}="Cancelado";
		TICKET{2,i}=0; /* <-- Inf. de ARPU depois igual a zero para os Cancelados */
		ARPU{2,i}=0;END;
		
	IF STATUS{1,i} IN("Fora do combo") THEN DO;
		ALONE=ALONE+1;
		STATUS{2,i}="Retido - Fora do combo";END;
	
	IF STATUS{1,i}="Dentro do combo - Associação" THEN DO;
		AQUISICAO=AQUISICAO+1;
		STATUS{2,i}="Retido - Associação da UGR";
		TICKET{1,i}=0; /* <-- Inf. de ARPU ANTES igual a zero para os adquiridos */
		ARPU{1,i}=0;END;

	IF STATUS{1,i}="-" THEN DO; STATUS{2,i}="-";END;

	IF RESULTADO IN ("CANCELADO") THEN DO;ARPU_OIT{2,i}=0;END;
	IF RESULTADO IN ("RETIDO_ARG") THEN DO;ARPU_OIT{2,i}=ARPU_OIT{1,i};END;

	ARPU{3,i}=ARPU{2,i} - ARPU{1,i}; /* <-- Calcula o Delta ARPU da base cada UGR*/
	TICKET{3,i}=TICKET{2,i} - TICKET{1,i}; /* <-- Calcula o Delta ARPU do faturado de cada UGR*/
	ARPU_OIT{3,i}=ARPU_OIT{2,i} - ARPU_OIT{1,i}; /* <-- Calcula o Delta ARPU da base e do faturado para o Oi Total e receita */
END;

/* Detalha os resultados de downgrade e cancelado */
IF RESULTADO="OFERTA_DOWN" AND CANCELADO=0 AND ALONE>0 THEN DETALHE_MIGDOWN_CANCEL="MigDown. - UGR Alone";
IF RESULTADO="OFERTA_DOWN" AND CANCELADO>0 AND ALONE=0 THEN DETALHE_MIGDOWN_CANCEL="MigDown. - Canc. UGR";
IF RESULTADO="OFERTA_DOWN" AND CANCELADO>0 AND ALONE>0 THEN DETALHE_MIGDOWN_CANCEL="MigDown. - Canc. UGR e UGR Alone";
IF RESULTADO="OFERTA_DOWN" AND CANCELADO>0 AND ALONE=0 AND STATUS{1,4}="Migrado para Pré" THEN DETALHE_MIGDOWN_CANCEL="MigDown. - Apenas Mig. p/ Pré";
IF RESULTADO="CANCELADO_ALONE" AND CANCELADO=0 THEN DETALHE_MIGDOWN_CANCEL="Canc. OIT - Desmembramento";
IF RESULTADO="CANCELADO_ALONE" AND CANCELADO>0 AND ALONE>0 THEN DETALHE_MIGDOWN_CANCEL="Canc. OIT - UGR Alone";
IF RESULTADO="CANCELADO_ALONE" AND CANCELADO>0 AND ALONE=0 AND STATUS{1,4}="Migrado para Pré" THEN DETALHE_MIGDOWN_CANCEL="Canc. OIT - Apenas Mig. p/ Pré";

PRODUTOS_MANTIDOS_ALONE=CATX("", 
TRANSTRN(COUNT(STATUS{1,1},"Fora do combo"),1,"FX"),
TRANSTRN(COUNT(STATUS{1,2},"Fora do combo"),1,"BL"),
TRANSTRN(COUNT(STATUS{1,3},"Fora do combo"),1,"TV"),
TRANSTRN(COUNT(STATUS{1,4},"Fora do combo"),1,"MV"));
PRODUTOS_MANTIDOS_ALONE=TRANSTRN(PRODUTOS_MANTIDOS_ALONE,"0 ",TRIMN(""));

PRODUTOS_CANCELADOS=CATX("", 
TRANSTRN(COUNT(STATUS{1,1},"Cancelado"),1,"FX"),
TRANSTRN(COUNT(STATUS{1,2},"Cancelado"),1,"BL"),
TRANSTRN(COUNT(STATUS{1,3},"Cancelado"),1,"TV"),
TRANSTRN(COUNT(STATUS{1,4},"Cancelado"),1,"MV"),
TRANSTRN(COUNT(STATUS{1,4},"Migrado para Pré"),1,"MV"));
PRODUTOS_CANCELADOS=TRANSTRN(PRODUTOS_CANCELADOS,"0 ",TRIMN(""));

DO i= 1 to 2;

	/* Padroniza o nome dos pacotes de cada UGR --> */	
	IF NOME_PAC{1,i} IN ("", "0", "Sem Benefi") THEN NOME_PAC{1,i}="N/D";
	IF NOME_PAC{2,i} IN ("", "0", "Sem Benefi") THEN NOME_PAC{2,i}="N/D";
	NOME_PAC{3,i}= CATX(" | ", "Ilim", NOME_PAC{1,i}, NOME_PAC{2,i});

	NOME_PAC{4,i}=TRANSTRN(COMPRESS(NOME_PAC{4,i}),"MB","000");
	NOME_PAC{4,i}=TRANSTRN(COMPRESS(NOME_PAC{4,i}),"KB",TRIMN(''));
	NOME_PAC{4,i}=TRANSTRN(NOME_PAC{4,i},".0",TRIMN(''));

	NOME_PAC{5,i}=TRANSTRN(UPCASE(NOME_PAC{5,i}),"OI ",TRIMN('')); 
	NOME_PAC{5,i}=TRANSTRN(UPCASE(NOME_PAC{5,i}),"TV ",TRIMN(''));

	NOME_PAC{6,i}=TRANSTRN(COMPRESS(NOME_PAC{6,i}),"MB",TRIMN(''));
	NOME_PAC{6,i}=TRANSTRN(COMPRESS(NOME_PAC{6,i}),"GB","000");
	NOME_PAC{6,i}=TRANSTRN(NOME_PAC{6,i},".0",TRIMN(''));

	/* Flag ARPU --> */
	IF (BUNDLE{i}="2P BL" AND (ARPU{i,1}<15 OR ARPU{i,2}<15)) 
	OR (BUNDLE{i}="2P TV" AND (ARPU{i,1}<15 OR ARPU{i,3}<20))
	OR (BUNDLE{i}="3P MOVEL" AND (ARPU{i,1}<15 OR ARPU{i,2}<15 OR ARPU{i,4}<20))
	OR (BUNDLE{i}="3P RES" AND (ARPU{i,1}<15 OR ARPU{i,2}<15 OR ARPU{i,3}<20))
	OR (BUNDLE{i}="4P" AND (ARPU{i,1}<15 OR ARPU{i,2}<15 OR ARPU{i,3}<20 OR ARPU{i,4}<20))THEN FLAG_ARPU=1;

	/* Flag TICKET --> */
	IF (BUNDLE{i}="2P BL" AND (TICKET{i,1}<15 OR TICKET{i,2}<15)) 
	OR (BUNDLE{i}="2P TV" AND (TICKET{i,1}<15 OR TICKET{i,3}<20))
	OR (BUNDLE{i}="3P MOVEL" AND (TICKET{i,1}<15 OR TICKET{i,2}<15 OR TICKET{i,4}<20))
	OR (BUNDLE{i}="3P RES" AND (TICKET{i,1}<15 OR TICKET{i,2}<15 OR TICKET{i,3}<20))
	OR (BUNDLE{i}="4P" AND (TICKET{i,1}<15 OR TICKET{i,2}<15 OR TICKET{i,3}<20 OR TICKET{i,4}<20))THEN FLAG_TICKET=1;
END;


FLAG_VELOC_VLX=0;FLAG_VOZ=0;FLAG_DADOS=0;FLAG_TV=0;

/* Flag Velox --> */
IF BUNDLE{1} NOT="2P TV" THEN DO;
	IF NOME_PAC{4,1} NOT IN ("", "0", "-") THEN DO;
		IF STATUS{2,2}="Retido - Argumentação" THEN	DO;
			NOME_PAC{4,2}=NOME_PAC{4,1};END;
		IF STATUS{2,2}="Cancelado" THEN	DO;
			NOME_PAC{4,2}="-";END;	
		IF STATUS{2,2} IN ("Retido - Oferta Dentro do OIT", "Retido - Fora do combo") THEN DO;
			IF NOME_PAC{4,2} IN ("", "0", "-") THEN DO;
				FLAG_VELOC_VLX=1;END;END;END;ELSE DO FLAG_VELOC_VLX=1;END;
END;

/* Flag TV --> */
IF BUNDLE{1} NOT IN ("3P MOVEL", "2P BL") THEN DO;
	IF NOME_PAC{5,1} NOT IN ("", "-") THEN DO;
		IF STATUS{2,3}="Retido - Argumentação" THEN DO;
			NOME_PAC{5,2}=NOME_PAC{5,1};END;
		IF STATUS{2,3}="Cancelado" THEN DO;
			NOME_PAC{5,2}="-";END;	
		IF STATUS{2,3} IN ("Retido - Oferta Dentro do OIT", "Retido - Fora do combo") THEN DO;
			IF NOME_PAC{5,2} IN ("", "-") THEN DO;
				FLAG_TV=1;END;END;END;ELSE DO FLAG_TV=1;END;
END;

/* Flag Dados --> */
IF BUNDLE{1} IN ("3P MOVEL","4P") THEN DO;
	IF NOME_PAC{6,1} NOT IN ("", "-") THEN DO;
		IF STATUS{2,4}="Retido - Argumentação" THEN DO;
			NOME_PAC{6,2}=NOME_PAC{6,1};END;
		IF STATUS{2,4}="Cancelado" THEN DO;
			NOME_PAC{6,2}="-";END;	
		IF STATUS{2,4} IN ("Retido - Oferta Dentro do OIT", "Retido - Fora do combo") THEN DO;
			IF NOME_PAC{6,2} IN ("", "-") THEN DO;
				FLAG_DADOS=1;END;END;END;ELSE DO FLAG_DADOS=1;END;
END;

/* Flag Voz --> */
IF BUNDLE{1} IN ("3P MOVEL","4P") THEN DO;
	IF NOME_PAC{7,1} NOT IN ("", "0", "-") THEN	DO;
		IF STATUS{2,4}="Retido - Argumentação" THEN	DO;
			NOME_PAC{7,2}=NOME_PAC{7,1};END;
		IF STATUS{2,4}="Cancelado" THEN DO;
			NOME_PAC{7,2}="-";END;	
		IF STATUS{2,4} IN ("Retido - Oferta Dentro do OIT", "Retido - Fora do combo") THEN DO;
			IF NOME_PAC{7,2} IN ("", "0", "-") THEN DO;
				FLAG_VOZ=1;END;END;END;ELSE DO FLAG_VOZ=1;END;
END;

ARRAY UGR{2,4} FX BL TV MV FX_END BL_END TV_END MV_END;
DO i= 1 to 4;
IF STATUS{1,i} IN ("Dentro do combo - Mantido","Cancelado","Fora do combo") THEN UGR{1,i}=1;ELSE UGR{1,i}=0;
END;

IF INDEX(UGR_BUNDLE,"1") NOT=0 THEN UGR{2,1}=1;ELSE UGR{2,1}=0;
IF INDEX(UGR_BUNDLE,"2") NOT=0 THEN UGR{2,2}=1;ELSE UGR{2,2}=0;
IF INDEX(UGR_BUNDLE,"3") NOT=0 THEN UGR{2,3}=1;ELSE UGR{2,3}=0;
IF INDEX(UGR_BUNDLE,"4") NOT=0 THEN UGR{2,4}=1;ELSE UGR{2,4}=0;

/* Cria o índice de duplicidade --> */
IF RESULTADO_DA_CHAMADA IN ("Cancelado") THEN IND_DUPLICIDADE = 1; ELSE 
IF DETALHE_RESULTADO_DA_CHAMADA IN ("Retido com Oferta - Com Retirada") THEN IND_DUPLICIDADE = 2; ELSE
IF DETALHE_RESULTADO_DA_CHAMADA IN ("Retido com Oferta - Com Inclusão e Retirada") THEN IND_DUPLICIDADE = 3; ELSE
IF DETALHE_RESULTADO_DA_CHAMADA IN ("Retido com Oferta - Com Inclusão") THEN IND_DUPLICIDADE = 4; ELSE
IF DETALHE_RESULTADO_DA_CHAMADA IN ("Retido com Oferta - Mesmo Combo") THEN IND_DUPLICIDADE = 5; ELSE
IF DETALHE_RESULTADO_DA_CHAMADA IN ("Retido com Argumentação / Ação") THEN IND_DUPLICIDADE = 6; ELSE
IND_DUPLICIDADE = 7;

DROP UGR_BUNDLE i k RESULTADO_NEW STATUS_FX_BL_TV_MV;
RUN;

/* Remove REGISTROS duplicados --> */
PROC SORT DATA=OIT.CHAMADAS_&MES._TITULAR_OIT_FB NODUPKEY; BY ID_REGISTRO_CHAMADA; RUN;

%MEND IMPORT_NBA;
%IMPORT_NBA

