OPTIONS COMPRESS = YES 
		REUSE = YES
		OBS = MAX;

LIBNAME AD_HOC   	"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/AD_HOC/DANIEL";
LIBNAME PLANTA   	"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/PLNT/FIXO_BL_TV";
LIBNAME RET_FX   	"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RETIRADAS/FIXO";
LIBNAME RET_BL   	"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RETIRADAS/VELOX";
LIBNAME RET_TV   	"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RETIRADAS/TV";
LIBNAME RET_OiT  	"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RETIRADAS/OiTotal";
LIBNAME INS_OiT  	"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RETIRADAS/OiTotal/Gross_OiT";
LIBNAME TV  	 	"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/PLNT/TV";
LIBNAME GROSS   	"/sasdata/ger_trafego_mkt/AQUISICAO/GROSS";
LIBNAME DE_PARAS 	"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/DE_PARAs";
LIBNAME AD_HOC   	"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/AD_HOC/DANIEL";
LIBNAME REPARO 		"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/REPARO";
LIBNAME REPCONS		"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/REPARO/Consolidados";
LIBNAME RACO 		"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RACO";
LIBNAME NBA 		"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/NBA";
LIBNAME ASSIA  		"/sasdata/varejo/ger_var_banda_larga/Temporario_sera_apagado/ASSIA";
LIBNAME CONTEST 	"/sasdata/varejo/ger_var_banda_larga/Contestacao/Bases";
LIBNAME CONTCONS 	"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/CONTESTACAO/CONSOLIDADOS";
LIBNAME WAR			"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/WAR";
LIBNAME PORT 		"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/SOLICITACOES_PORTABILIDADE";
LIBNAME BLIND 		"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/BLINDAGEM/CLAUDIO";
LIBNAME RET_POS 	"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RETIRADAS/MOVEL";
LIBNAME REC 	 	"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RECARGA";
LIBNAME ORC 		"/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/ORCAMENTO/OUTPUTS";

/**************************************************************************************************************/
/**************************************************************************************************************/
/********** 1 - Cadastro: Planta de FIXO, BL, TV e OIT                                          ***************/
/********** 2 - Contact Rate: Chamadas na Retenção Alone e Oi Total                             ***************/
/********** 3 - Outros Canais: Raco e Portabilidade          								    ***************/
/********** 4 - Qualidade: Reparo, Contestação e Medição Assia          						***************/
/********** 5 - Churn: Retiradas de Fixo, BL, TV e OiT					 						***************/
/********** 6 - Faturamento: Valor faturado recorrente Fixo, BL, TV e OiT* 	TBD    	 		    ***************/
/**************************************************************************************************************/
/**************************************************************************************************************/

%MACRO ORC (MESMENOS2,MESMENOS1,MES,MESMAIS1,MESMAIS2,MESMAIS3);

/***************************************************************************************************************/
/* Planta Residencial  *****************************************************************************************/
/***************************************************************************************************************/

/*Planta produtos M-1 */

DATA STEP_01_PLANTA_&MESMENOS1.; 
SET  PLANTA.PLANTA_FX_BL_TV_&MESMENOS1. 
(KEEP = REGIAO UF MUNICIPIO ESTACAO DDD_TELEFONE POSSE_GERENCIAL_RESIDENCIAL POSSE_GERENCIAL_COMPLETA POSSE_OCT TEMPO_BASE_FX TEMPO_BASE_BL TEMPO_BASE_TV VELOC_ATUAL ZONA_CIDADE CONTRATO_TV PONTO_ADICIONAL_TV DESC_FORMA_PAGTO_TV PLANO_TV MIX_PCT_ATUAL_TV TIPO_CONTRATO_TV);
ANOMES_PLANTA=&MESMENOS1.;
/*IF POSSE_GERENCIAL_RESIDENCIAL NOT IN ('1P-TV'/*,'2P-TV','1P-Fixo');*/

INFORMAT AGING_FX $20.;
	IF TEMPO_BASE_FX <= 3 THEN AGING_FX = '0_M0aM3'; ELSE
	IF TEMPO_BASE_FX > 3 THEN  AGING_FX = '1_M4+'; ELSE
	AGING_FX='';

INFORMAT AGING_BL $20.;
	IF TEMPO_BASE_BL <= 3 THEN AGING_BL = '0_M0aM3'; ELSE
	IF TEMPO_BASE_BL > 3 THEN  AGING_BL = '1_M4+'; ELSE
	AGING_BL='';


INFORMAT AGING_TV $20.;
	IF TEMPO_BASE_TV <= 3 THEN AGING_TV = '0_M0aM3'; ELSE
	IF TEMPO_BASE_TV > 3 THEN  AGING_TV = '1_M4+'; ELSE
	AGING_TV='';

INFORMAT TIPO_TV $30.;
	IF TIPO_CONTRATO_TV = "BRI DTH" THEN TIPO_TV = 'Anteneiro'; ELSE
	IF TIPO_CONTRATO_TV IN ("NORMAL DTH","ESPECIAL DTH","CONDOMÍNIO DTH","Corporativo DTH","COLABORADOR DTH") THEN TIPO_TV = 'Comodato';ELSE
	TIPO_TV = '';
RUN;

PROC SORT DATA=STEP_01_PLANTA_&MESMENOS1.;BY DDD_TELEFONE;RUN;

/*Posse posterior*/

DATA STEP_01_POSSE_POSTERIOR_&MESMAIS1.;
SET  PLANTA.PLANTA_FX_BL_TV_&MESMAIS1. 
(KEEP = DDD_TELEFONE CONTRATO_TV POSSE_GERENCIAL_RESIDENCIAL POSSE_GERENCIAL_COMPLETA);

RENAME POSSE_GERENCIAL_RESIDENCIAL=POSSE_RESIDENCIAL_MESMAIS1;
RENAME POSSE_GERENCIAL_COMPLETA=POSSE_RESIDENCIAL_II_MESMAIS1;

IF DDD_TELEFONE NE '';

RUN;

PROC SORT DATA=STEP_01_POSSE_POSTERIOR_&MESMAIS1. NODUPKEY;BY DDD_TELEFONE;RUN;

/***************************************************************************************************************/
/* Planta Oi Total  ********************************************************************************************/
/***************************************************************************************************************/

/*M-1*/

DATA STEP_01_PLANTA_OIT_&MESMENOS1.;
SET  PLANTA.PLANTA_OI_TOTAL_BI_&MESMENOS1. (KEEP= DDD_TELEFONE DDD_MOVEL_TITULAR CPFCNPJ_TITULAR ID_BUNDLE TIPO_EVENTO_VENDA TP_POSSE_ATUAL AGING_BUNDLE QTD_BUNDLE);
IF QTD_BUNDLE=1;
POSSE_OIT=1;
IF DDD_TELEFONE NE '';

INFORMAT AGING_OIT $20.;
	IF AGING_BUNDLE <= 3 THEN AGING_OIT = '0_M0aM3'; ELSE
	IF AGING_BUNDLE > 3 THEN  AGING_OIT = '1_M4+'; ELSE
	AGING_OIT='';
RUN;


RUN;
PROC SORT DATA= STEP_01_PLANTA_OIT_&MESMENOS1. NODUPKEY; BY DDD_TELEFONE;RUN;

/*M-2*/

DATA STEP_01_PLANTA_OIT_&MESMENOS2.;
SET  PLANTA.PLANTA_OI_TOTAL_BI_&MESMENOS2. (KEEP= DDD_TELEFONE CPFCNPJ_TITULAR TIPO_EVENTO_VENDA ID_BUNDLE TP_POSSE_ATUAL QTD_BUNDLE);
IF QTD_BUNDLE=1;
RENAME TP_POSSE_ATUAL = TIPO_POSSE_ATUAL_MESMENOS2;
RENAME TIPO_EVENTO_VENDA = TIPO_EVENTO_VENDA_MESMENOS2;
IF DDD_TELEFONE NE '';
RUN;
PROC SORT DATA= STEP_01_PLANTA_OIT_&MESMENOS2. NODUPKEY; BY DDD_TELEFONE;RUN;

/*M+1*/

DATA STEP_01_PLANTA_OIT_&MESMAIS1.;
SET  PLANTA.PLANTA_OI_TOTAL_BI_&MESMAIS1. (KEEP= DDD_TELEFONE CPFCNPJ_TITULAR TIPO_EVENTO_VENDA ID_BUNDLE TP_POSSE_ATUAL QTD_BUNDLE);
IF QTD_BUNDLE=1;
RENAME TP_POSSE_ATUAL = TIPO_POSSE_ATUAL_MESMAIS1;
RENAME TIPO_EVENTO_VENDA = TIPO_EVENTO_VENDA_MESMAIS1;
IF DDD_TELEFONE NE '';
RUN;
PROC SORT DATA= STEP_01_PLANTA_OIT_&MESMAIS1. NODUPKEY; BY DDD_TELEFONE;RUN;

/***************************************************************************************************************/
/* Planta Voz Total ********************************************************************************************/
/***************************************************************************************************************/

DATA STEP_01_PLANTA_VOZ_TOTAL_&MESMENOS1.;
SET  REC.PLANTA_RECARGA_&MESMENOS1. (KEEP= DDD_TELEFONE);
POSSE_VOZ_TOTAL=1;
IF DDD_TELEFONE >0;
RUN;
PROC SORT DATA= STEP_01_PLANTA_VOZ_TOTAL_&MESMENOS1. NODUPKEY; BY DDD_TELEFONE;RUN;


/* Cruza Plantas */

DATA  	STEP_01_PLANTA_&MESMENOS1.;
MERGE 	STEP_01_PLANTA_&MESMENOS1. 			(IN=A)
		STEP_01_POSSE_POSTERIOR_&MESMAIS1.	(IN=B KEEP=DDD_TELEFONE POSSE_RESIDENCIAL_MESMAIS1 POSSE_RESIDENCIAL_II_MESMAIS1)
		STEP_01_PLANTA_OIT_&MESMENOS1.		(IN=C KEEP=DDD_TELEFONE DDD_MOVEL_TITULAR ID_BUNDLE TIPO_EVENTO_VENDA TP_POSSE_ATUAL AGING_OIT)
		STEP_01_PLANTA_OIT_&MESMENOS2.		(IN=D KEEP=DDD_TELEFONE TIPO_POSSE_ATUAL_MESMENOS2 TIPO_EVENTO_VENDA_MESMENOS2)
		STEP_01_PLANTA_OIT_&MESMAIS1.		(IN=E KEEP=DDD_TELEFONE TIPO_POSSE_ATUAL_MESMAIS1 TIPO_EVENTO_VENDA_MESMAIS1)
		STEP_01_PLANTA_VOZ_TOTAL_&MESMENOS1.(IN=F);
BY DDD_TELEFONE;
IF A;
RUN;

/***************************************************************************************************************/
/* Chamadas na Retenção ****************************************************************************************/
/***************************************************************************************************************/

/*M0*/

DATA CHAMADAS_RETENCAO_&MES.;
SET NBA.NBA_RET_CHAMADAS_&MES. (KEEP= DDD_TELEFONE ID_OPERADOR DT_CRIACAO CLASSERETIDO CLASSERETIDOFIXO CLASSERETIDOVELOX TP_CHAMADA PRODUTO);
IF TP_CHAMADA = "Produtiva";
IF CLASSERETIDO IN ("RETIDO COM OFERTA NO NBA","Não Retido") THEN IND_DUPLICIDADE = 1; ELSE IND_DUPLICIDADE = 0;
RENAME ID_OPERADOR = MATRICULA;
ANOMES = &MES.;
IF DDD_TELEFONE>0;

INFORMAT IND_RETENCAO_MES $30.;
IF CLASSERETIDO = "RETIDO COM OFERTA NO NBA" 	THEN IND_RETENCAO_MES = "2_Retido_com_Oferta";ELSE
IF CLASSERETIDO = "RETIDO COM ARGUMENTACAO" 	THEN IND_RETENCAO_MES = "3_Retido_sem_Oferta";ELSE
IF CLASSERETIDO = "Não Retido" 					THEN IND_RETENCAO_MES = "1_Não_retido"; ELSE
IND_RETENCAO_MES = "0_Não_passou_na_retenção";

RUN;

PROC SORT DATA=CHAMADAS_RETENCAO_&MES.; BY DDD_TELEFONE DESCENDING IND_DUPLICIDADE DESCENDING DT_CRIACAO; RUN;
PROC SORT DATA=CHAMADAS_RETENCAO_&MES. NODUPKEY; BY DDD_TELEFONE; RUN;

DATA MATRICULAS_BO_OCT;
SET WAR.MATRICULAS___BO_OCT;
IF ANOMES = &MES.;
BO_OCT=1;
RUN;

PROC SORT DATA=MATRICULAS_BO_OCT; BY MATRICULA; RUN;
PROC SORT DATA=CHAMADAS_RETENCAO_&MES.;BY MATRICULA; RUN;

DATA  CHAMADAS_RETENCAO_&MES.;
MERGE CHAMADAS_RETENCAO_&MES.  	 	  (IN=A)
      MATRICULAS_BO_OCT   	 		  (IN=B);
BY MATRICULA;
IF A;
IF BO_OCT=.;
RUN;

/*M-1*/

DATA CHAMADAS_RETENCAO_&MESMENOS1.;
SET NBA.NBA_RET_CHAMADAS_&MESMENOS1. (KEEP= DDD_TELEFONE ID_OPERADOR DT_CRIACAO CLASSERETIDO CLASSERETIDOFIXO CLASSERETIDOVELOX TP_CHAMADA PRODUTO);
IF TP_CHAMADA = "Produtiva";
IF CLASSERETIDO IN ("RETIDO COM OFERTA NO NBA","Não Retido") THEN IND_DUPLICIDADE = 1; ELSE IND_DUPLICIDADE = 0;
RENAME ID_OPERADOR = MATRICULA;
ANOMES = &MESMENOS1.;
IF DDD_TELEFONE>0;

INFORMAT IND_RETENCAO_MESMENOS1 $30.;
IF CLASSERETIDO = "RETIDO COM OFERTA NO NBA" 	THEN IND_RETENCAO_MESMENOS1 = "2_Retido_com_Oferta";ELSE
IF CLASSERETIDO = "RETIDO COM ARGUMENTACAO" 	THEN IND_RETENCAO_MESMENOS1 = "3_Retido_sem_Oferta";ELSE
IF CLASSERETIDO = "Não Retido" 					THEN IND_RETENCAO_MESMENOS1 = "1_Não_retido"; ELSE
IND_RETENCAO_MESMENOS1 = "0_Não_passou_na_retenção";

RUN;

PROC SORT DATA=CHAMADAS_RETENCAO_&MESMENOS1.; BY DDD_TELEFONE DESCENDING IND_DUPLICIDADE DESCENDING DT_CRIACAO; RUN;
PROC SORT DATA=CHAMADAS_RETENCAO_&MESMENOS1. NODUPKEY; BY DDD_TELEFONE; RUN;

DATA MATRICULAS_BO_OCT;
SET WAR.MATRICULAS___BO_OCT;
IF ANOMES = &MESMENOS1.;
BO_OCT=1;
RUN;

PROC SORT DATA=MATRICULAS_BO_OCT; BY MATRICULA; RUN;
PROC SORT DATA=CHAMADAS_RETENCAO_&MESMENOS1.;BY MATRICULA; RUN;

DATA  CHAMADAS_RETENCAO_&MESMENOS1.;
MERGE CHAMADAS_RETENCAO_&MESMENOS1.   (IN=A)
      MATRICULAS_BO_OCT   	 		  (IN=B);
BY MATRICULA;
IF A;
IF BO_OCT=.;
RUN;

/***************************************************************************************************************/
/* Chamadas TV *******************************************************************************************/
/***************************************************************************************************************/

DATA CHAMADAS_RETENCAO_TV_NBA_&MES.;
SET  NBA.BTCC_RETENCAO_NBA_TV_&MES. 			(KEEP=NUM_CONTRATO_TV TP_CHAMADA RESULTADO)
	 NBA.CONTAX_RETENCAO_NBA_TV_&MES.			(KEEP=NUM_CONTRATO_TV TP_CHAMADA RESULTADO);

IF TP_CHAMADA = "Produtiva";

INFORMAT IND_RETENCAO_TV_MES $30.;
IF RESULTADO IN ("Retido apenas com oferta de isenção de ponto","Retido com oferta","Retido com serviços") 	THEN IND_RETENCAO_TV_MES = "2_Retido_com_Oferta";ELSE
IF RESULTADO IN ("Retido com argumentação","Retido com argumentação de multa") 	THEN IND_RETENCAO_TV_MES = "3_Retido_sem_Oferta";ELSE
IF RESULTADO = "Não Retido" 													THEN IND_RETENCAO_TV_MES = "1_Não_retido"; ELSE
IND_RETENCAO_TV_MES = "0_Não_passou_na_retenção";
RUN;
PROC SORT DATA=CHAMADAS_RETENCAO_TV_NBA_&MES. NODUPKEY; BY NUM_CONTRATO_TV; RUN;

DATA CHAMADAS_RETENCAO_TV_NBA_&MESMENOS1.;
SET  NBA.BTCC_RETENCAO_NBA_TV_&MESMENOS1. 			(KEEP=NUM_CONTRATO_TV TP_CHAMADA RESULTADO)
	 NBA.CONTAX_RETENCAO_NBA_TV_&MESMENOS1.			(KEEP=NUM_CONTRATO_TV TP_CHAMADA RESULTADO);

IF TP_CHAMADA = "Produtiva";

INFORMAT IND_RETENCAO_TV_MESMENOS1 $30.;
IF RESULTADO IN ("Retido apenas com oferta de isenção de ponto","Retido com oferta","Retido com serviços") 	THEN IND_RETENCAO_TV_MESMENOS1 = "2_Retido_com_Oferta";ELSE
IF RESULTADO IN ("Retido com argumentação","Retido com argumentação de multa") 	THEN IND_RETENCAO_TV_MESMENOS1 = "3_Retido_sem_Oferta";ELSE
IF RESULTADO = "Não Retido" 													THEN IND_RETENCAO_TV_MESMENOS1 = "1_Não_retido"; ELSE
IND_RETENCAO_TV_MESMENOS1 = "0_Não_passou_na_retenção";
RUN;
PROC SORT DATA=CHAMADAS_RETENCAO_TV_NBA_&MESMENOS1. NODUPKEY; BY NUM_CONTRATO_TV; RUN;


DATA CHAMADAS_RETENCAO_TV_&MES.;
SET  NBA.BTCC_RETENCAO_TV_&MES. 			(KEEP=DSCONTRATO DSTIPOCHAMADA DSMOTIVORETENCAO)
	 NBA.CONTAX_RETENCAO_TV_&MES.			(KEEP=DSCONTRATO DSTIPOCHAMADA DSMOTIVORETENCAO);

IF DSTIPOCHAMADA = "PRODUTIVA";

INFORMAT IND_RETENCAO_TV_MES $30.;
IF DSMOTIVORETENCAO IN ("RETIDO COM OFERTA MULTIPRODUTOS","RETIDO COM OFERTA TV","RETIDO COM SERVICOS") 	THEN IND_RETENCAO_TV_MES = "2_Retido_com_Oferta";ELSE
IF DSMOTIVORETENCAO IN ("REVERTIDO COM ARGUMENTACAO","REVERTIDO COM MULTA") 	THEN IND_RETENCAO_TV_MES = "3_Retido_sem_Oferta";ELSE
IF DSMOTIVORETENCAO = "NAO SE APLICA" 												THEN IND_RETENCAO_TV_MES = "1_Não_retido"; ELSE
IND_RETENCAO_TV_MES = "0_Não_passou_na_retenção";

RENAME DSCONTRATO = NUM_CONTRATO_TV;
RENAME DSTIPOCHAMADA = TP_CHAMADA;
RENAME DSMOTIVORETENCAO = RESULTADO;

RUN;
PROC SORT DATA=CHAMADAS_RETENCAO_TV_&MES. NODUPKEY; BY NUM_CONTRATO_TV; RUN;

DATA CHAMADAS_RETENCAO_TV_&MESMENOS1.;
SET  NBA.BTCC_RETENCAO_TV_&MESMENOS1. 			(KEEP=DSCONTRATO DSTIPOCHAMADA DSMOTIVORETENCAO)
	 NBA.CONTAX_RETENCAO_TV_&MESMENOS1.			(KEEP=DSCONTRATO DSTIPOCHAMADA DSMOTIVORETENCAO);

IF DSTIPOCHAMADA = "PRODUTIVA";

INFORMAT IND_RETENCAO_TV_MESMENOS1 $30.;
IF DSMOTIVORETENCAO IN ("RETIDO COM OFERTA MULTIPRODUTOS","RETIDO COM OFERTA TV","RETIDO COM SERVICOS") 	THEN IND_RETENCAO_TV_MESMENOS1 = "2_Retido_com_Oferta";ELSE
IF DSMOTIVORETENCAO IN ("REVERTIDO COM ARGUMENTACAO","REVERTIDO COM MULTA") 	THEN IND_RETENCAO_TV_MESMENOS1 = "3_Retido_sem_Oferta";ELSE
IF DSMOTIVORETENCAO = "NAO SE APLICA" 												THEN IND_RETENCAO_TV_MESMENOS1 = "1_Não_retido"; ELSE
IND_RETENCAO_TV_MESMENOS1 = "0_Não_passou_na_retenção";

RENAME DSCONTRATO = NUM_CONTRATO_TV;
RENAME DSTIPOCHAMADA = TP_CHAMADA;
RENAME DSMOTIVORETENCAO = RESULTADO;

RUN;
PROC SORT DATA=CHAMADAS_RETENCAO_TV_&MESMENOS1. NODUPKEY; BY NUM_CONTRATO_TV; RUN;

DATA CHAMADAS_RETENCAO_TV_FULL_&MES.;
SET  CHAMADAS_RETENCAO_TV_NBA_&MES.
	 CHAMADAS_RETENCAO_TV_&MES.;
	 IF NUM_CONTRATO_TV>0;
RUN;
PROC SORT DATA=CHAMADAS_RETENCAO_TV_FULL_&MES. NODUPKEY; BY NUM_CONTRATO_TV; RUN;


DATA CHAMADAS_RETENCAO_TV_FULL_&MESMENOS1.;
SET  CHAMADAS_RETENCAO_TV_NBA_&MESMENOS1.
	 CHAMADAS_RETENCAO_TV_&MESMENOS1.;
	 IF NUM_CONTRATO_TV>0;
RUN;
PROC SORT DATA=CHAMADAS_RETENCAO_TV_FULL_&MESMENOS1. NODUPKEY; BY NUM_CONTRATO_TV; RUN;


/***************************************************************************************************************/
/* Chamadas Oi Total *******************************************************************************************/
/***************************************************************************************************************/

DATA CHAMADAS_OITotal_&MES.;
SET NBA.CHAMADAS_OIT_&MES. (KEEP= ID_BUNDLE RESULTADO RESULTADO2);
ANOMES = &MES.;

INFORMAT IND_RETENCAO_OIT_MES $30.;
IF RESULTADO2 IN ("Retido com Oferta","Retido com Migracao","Retido com Migração","Retido com Oferta Lateral","Retido com Oferta de Downgrade","Retido com Oferta de Upgrade") THEN IND_RETENCAO_OIT_MES = "2_Retido_com_Oferta";ELSE
IF RESULTADO2 IN ("Retido com Acao","Retido com Argumentacao","Retido com Argumentacao de Multa","Retido com Argumentação","Retido com Argumentação de Multa","Retido com Ação","Retido com Credito em Confianca","Retido com Crédito em Confiança","Retido com Migracao","Retido com Migração","Retido com Oferta Lateral","Retido com Oferta de Downgrade","Retido com Oferta de Upgrade") THEN IND_RETENCAO_OIT_MES = "3_Retido_sem_Oferta";ELSE
IF RESULTADO2 IN ("Cancelado com isenção de multa","Cancelado com retirada de flag de inadimplência","Cancelado oriundo de migração massiva","Cancelado sem isenção de multa","Cancelamento de todos os produtos do Oi total","Desmembramento dos produtos Oi total") THEN IND_RETENCAO_OIT_MES = "1_Não_retido"; ELSE
IND_RETENCAO_OIT_MES = "0_Não_passou_na_retenção";

IF ID_BUNDLE NE '';

RUN;

PROC SORT DATA=CHAMADAS_OITotal_&MES. NODUPKEY;BY ID_BUNDLE;RUN;


DATA CHAMADAS_OITotal_&MESMENOS1.;
SET NBA.CHAMADAS_OIT_&MESMENOS1. (KEEP= ID_BUNDLE RESULTADO RESULTADO2);
ANOMES = &MESMENOS1.;

INFORMAT IND_RETENCAO_OIT_MESMENOS1 $30.;
IF RESULTADO2 IN ("Retido com Oferta","Retido com Migracao","Retido com Migração","Retido com Oferta Lateral","Retido com Oferta de Downgrade","Retido com Oferta de Upgrade") THEN IND_RETENCAO_OIT_MESMENOS1 = "2_Retido_com_Oferta";ELSE
IF RESULTADO2 IN ("Retido com Acao","Retido com Argumentacao","Retido com Argumentacao de Multa","Retido com Argumentação","Retido com Argumentação de Multa","Retido com Ação","Retido com Credito em Confianca","Retido com Crédito em Confiança","Retido com Migracao","Retido com Migração","Retido com Oferta Lateral","Retido com Oferta de Downgrade","Retido com Oferta de Upgrade") THEN IND_RETENCAO_OIT_MESMENOS1 = "3_Retido_sem_Oferta";ELSE
IF RESULTADO2 IN ("Cancelado com isenção de multa","Cancelado com retirada de flag de inadimplência","Cancelado oriundo de migração massiva","Cancelado sem isenção de multa","Cancelamento de todos os produtos do Oi total","Desmembramento dos produtos Oi total") THEN IND_RETENCAO_OIT_MESMENOS1 = "1_Não_retido"; ELSE
IND_RETENCAO_OIT_MESMENOS1 = "0_Não_passou_na_retenção";

IF ID_BUNDLE NE '';

RUN;

PROC SORT DATA=CHAMADAS_OITotal_&MESMENOS1. NODUPKEY;BY ID_BUNDLE;RUN;


/***************************************************************************************************************/
/* Blindagem e Refidel *****************************************************************************************/
/***************************************************************************************************************/

DATA BLIND_&MESMENOS1.;
SET  /*BLIND.BLINDAGEM_&MES. 		 	(KEEP= ID_TERMINAL MOTIVO_RACO)*/
	 BLIND.BLINDAGEM_&MESMENOS1. 	(KEEP= ID_TERMINAL MOTIVO_RACO)
	 /*BLIND.BLIND_REFIDEL_&MES. 	 	(KEEP= ID_TERMINAL MOTIVO_RACO)*/
	 BLIND.BLIND_REFIDEL_&MESMENOS1. (KEEP= ID_TERMINAL MOTIVO_RACO);

INFORMAT IND_BLINDAGEM $30.;
IF MOTIVO_RACO = "Venda" 								THEN IND_BLINDAGEM = "1_Venda";ELSE
IF MOTIVO_RACO = "Não Venda" 							THEN IND_BLINDAGEM = "2_Nao_venda"; ELSE
IF MOTIVO_RACO IN ("Cliente Não Elegível","Telefonia") 	THEN IND_BLINDAGEM = "3_Outros";ELSE
IND_BLINDAGEM = "3_Outros";

RENAME ID_TERMINAL = DDD_TELEFONE;

RUN;


PROC SORT DATA= BLIND_&MESMENOS1. ;BY DDD_TELEFONE IND_BLINDAGEM;RUN;
PROC SORT DATA= BLIND_&MESMENOS1. NODUPKEY;BY DDD_TELEFONE IND_BLINDAGEM;RUN;

/***************************************************************************************************************/
/* RACO ********************************************************************************************************/
/***************************************************************************************************************/

DATA RACO_2M_&MES.;
SET  RACO.RET_RACO_&MES. 						(KEEP=DDD_TELEFONE)
	 RACO.RET_RACO_&MESMENOS1.					(KEEP=DDD_TELEFONE);
IF DDD_TELEFONE>0;
IND_RACO=1;
RUN;
PROC SORT DATA= RACO_2M_&MES. NODUPKEY;BY DDD_TELEFONE;RUN;

/***************************************************************************************************************/
/* PORTABILIDADE ***********************************************************************************************/
/***************************************************************************************************************/

DATA PORTABILIDADE_2M_&MES.;
SET  PORT.PEDIDOS_PORTABILIDADE_&MES. 			(KEEP=DDD_TELEFONE)
	 PORT.PEDIDOS_PORTABILIDADE_&MESMENOS1.		(KEEP=DDD_TELEFONE);
IF DDD_TELEFONE>0;
IND_SOLIC_PORT=1;
RUN;
PROC SORT DATA= PORTABILIDADE_2M_&MES. NODUPKEY;BY DDD_TELEFONE;RUN;

/***************************************************************************************************************/
/* RETIRADAS ***********************************************************************************************/
/***************************************************************************************************************/

/* Retiradas Fixo M0 a M2 */

DATA RET_FX_&MES.;
SET  RET_FX.RETIRADOS_FIXO_&MES. (KEEP=DDD_TELEFONE FLAG_VOL);

IF FLAG_VOL=1 THEN CV_FX=&MES.;ELSE CV_FX=0;
IF FLAG_VOL=0 THEN CI_FX=&MES.;ELSE CI_FX=0;
CT_FX=&MES.;

KEEP DDD_TELEFONE CV_FX CI_FX CT_FX;
IF DDD_TELEFONE > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='';
END;
RUN;

DATA RET_FX_&MESMAIS1.;
SET  RET_FX.RETIRADOS_FIXO_&MESMAIS1. (KEEP=DDD_TELEFONE FLAG_VOL);

IF FLAG_VOL=1 THEN CV_FX_MESMAIS1=&MESMAIS1.;ELSE CV_FX_MESMAIS1=0;
IF FLAG_VOL=0 THEN CI_FX_MESMAIS1=&MESMAIS1.;ELSE CI_FX_MESMAIS1=0;
CT_FX_MESMAIS1=&MESMAIS1.;

KEEP DDD_TELEFONE CV_FX_MESMAIS1 CI_FX_MESMAIS1 CT_FX_MESMAIS1;
IF DDD_TELEFONE > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='';
END;
RUN;

/*DATA RET_FX_&MESMAIS2.;
SET  RET_FX.RETIRADOS_FIXO_&MESMAIS2. (KEEP=DDD_TELEFONE FLAG_VOL);

IF FLAG_VOL=1 THEN CV_FX_MESMAIS2=&MESMAIS2.;ELSE CV_FX_MESMAIS2=0;
IF FLAG_VOL=0 THEN CI_FX_MESMAIS2=&MESMAIS2.;ELSE CI_FX_MESMAIS2=0;
CT_FX_MESMAIS2=&MESMAIS2.;

KEEP DDD_TELEFONE CV_FX_MESMAIS2 CI_FX_MESMAIS2 CT_FX_MESMAIS2;
IF DDD_TELEFONE > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='';
END;
RUN;*/

/* Retiradas BL M0 a M2 */

DATA RET_BL_&MES.;
SET  RET_BL.RETIRADOS_VELOX_NEW_&MES. (KEEP=DDD_TELEFONE FLAG_VOL);

IF FLAG_VOL=1 THEN CV_BL=&MES.;ELSE CV_BL=0;
IF FLAG_VOL=0 THEN CI_BL=&MES.;ELSE CI_BL=0;
CT_BL=&MES.;

KEEP DDD_TELEFONE CV_BL CI_BL CT_BL;
IF DDD_TELEFONE > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='';
END;
RUN;

DATA RET_BL_&MESMAIS1.;
SET  RET_BL.RETIRADOS_VELOX_NEW_&MESMAIS1. (KEEP=DDD_TELEFONE FLAG_VOL);

IF FLAG_VOL=1 THEN CV_BL_MESMAIS1=&MESMAIS1.;ELSE CV_BL_MESMAIS1=0;
IF FLAG_VOL=0 THEN CI_BL_MESMAIS1=&MESMAIS1.;ELSE CI_BL_MESMAIS1=0;
CT_BL_MESMAIS1=&MESMAIS1.;

KEEP DDD_TELEFONE CV_BL_MESMAIS1 CI_BL_MESMAIS1 CT_BL_MESMAIS1;
IF DDD_TELEFONE > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='';
END;
RUN;

/*DATA RET_BL_&MESMAIS2.;
SET  RET_BL.RETIRADOS_VELOX_NEW_&MESMAIS2. (KEEP=DDD_TELEFONE FLAG_VOL);

IF FLAG_VOL=1 THEN CV_BL_MESMAIS2=&MESMAIS2.;ELSE CV_BL_MESMAIS2=0;
IF FLAG_VOL=0 THEN CI_BL_MESMAIS2=&MESMAIS2.;ELSE CI_BL_MESMAIS2=0;
CT_BL_MESMAIS2=&MESMAIS2.;

KEEP DDD_TELEFONE CV_BL_MESMAIS2 CI_BL_MESMAIS2 CT_BL_MESMAIS2;
IF DDD_TELEFONE > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='';
END;
RUN;*/


/* Retiradas + Mig Pós->Pré TV M0 a M2 */

DATA RET_TV_&MES.;
SET  RET_TV.RETIRADOS_TV_NEW_&MES. (KEEP=CONTRATO CPFCNPJ FLAG_VOL);
     
IF FLAG_VOL=1 THEN CV_TV=&MES.;ELSE CV_TV=0;
IF FLAG_VOL=0 THEN CI_TV=&MES.;ELSE CI_TV=0;
CT_TV=&MES.;

KEEP CONTRATO CV_TV CI_TV CT_TV;

IF CONTRATO > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='' ;
END;
RUN;

DATA MIGDOWN_TV_&MES.;
SET RET_TV.MIGRADOS_TV_&MES. (KEEP=INDICADOR CONTRATO);
IF INDICADOR = "MIGPOSPRE";
CV_TV=&MES.;
CI_TV=0;
CT_TV=&MES.;

KEEP CONTRATO CV_TV CI_TV CT_TV;

IF CONTRATO > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='' ;
END;
RUN;

DATA RET_MIGDOWN_TV_&MES.;
SET	 RET_TV_&MES.  
	 MIGDOWN_TV_&MES.;
RUN;


DATA RET_TV_&MESMAIS1.;
SET  RET_TV.RETIRADOS_TV_NEW_&MESMAIS1. (KEEP=CONTRATO CPFCNPJ FLAG_VOL);
     
IF FLAG_VOL=1 THEN CV_TV_MESMAIS1=&MESMAIS1.;ELSE CV_TV_MESMAIS1=0;
IF FLAG_VOL=0 THEN CI_TV_MESMAIS1=&MESMAIS1.;ELSE CI_TV_MESMAIS1=0;
CT_TV_MESMAIS1=&MESMAIS1.;

KEEP CONTRATO CV_TV_MESMAIS1 CI_TV_MESMAIS1 CT_TV_MESMAIS1;

IF CONTRATO > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='' ;
END;
RUN;

DATA MIGDOWN_TV_&MESMAIS1.;
SET RET_TV.MIGRADOS_TV_&MESMAIS1. (KEEP=INDICADOR CONTRATO);
IF INDICADOR = "MIGPOSPRE";
CV_TV_MESMAIS1=&MESMAIS1.;
CI_TV_MESMAIS1=0;
CT_TV_MESMAIS1=&MESMAIS1.;

KEEP CONTRATO CV_TV_MESMAIS1 CI_TV_MESMAIS1 CT_TV_MESMAIS1;

IF CONTRATO > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='' ;
END;
RUN;

DATA RET_MIGDOWN_TV_&MESMAIS1.;
SET	 RET_TV_&MESMAIS1.  
	 MIGDOWN_TV_&MESMAIS1.;
RUN;

/*DATA RET_TV_&MESMAIS2.;
SET  RET_TV.RETIRADOS_TV_NEW_&MESMAIS2. (KEEP=CONTRATO CPFCNPJ FLAG_VOL);
     
IF FLAG_VOL=1 THEN CV_TV_MESMAIS2=&MESMAIS2.;ELSE CV_TV_MESMAIS2=0;
IF FLAG_VOL=0 THEN CI_TV_MESMAIS2=&MESMAIS2.;ELSE CI_TV_MESMAIS2=0;
CT_TV_MESMAIS2=&MESMAIS2.;

KEEP CONTRATO CV_TV_MESMAIS2 CI_TV_MESMAIS2 CT_TV_MESMAIS2;

IF CONTRATO > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='' ;
END;
RUN;

DATA MIGDOWN_TV_&MESMAIS2.;
SET RET_TV.MIGRADOS_TV_&MESMAIS2. (KEEP=INDICADOR CONTRATO);
IF INDICADOR = "MIGPOSPRE";
CV_TV_MESMAIS2=&MESMAIS2.;
CI_TV_MESMAIS2=0;
CT_TV_MESMAIS2=&MESMAIS2.;

KEEP CONTRATO CV_TV_MESMAIS2 CI_TV_MESMAIS2 CT_TV_MESMAIS2;

IF CONTRATO > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='' ;
END;
RUN;

DATA RET_MIGDOWN_TV_&MESMAIS2.;
SET	 RET_TV_&MESMAIS2.  
	 MIGDOWN_TV_&MESMAIS2.;
RUN;*/


/* Retiradas Oi Total M0 a M2 */

DATA RET_OiT_&MES.;
SET RET_OiT.RETIRADAS_OI_TOTAL_&MES. (KEEP=ID_BUNDLE ORIGEM TP_RETIRADA TIPO_POSSE_RET);
     
IF TP_RETIRADA='VOL' THEN CV_OiT=&MES.;ELSE CV_OiT='';
IF TP_RETIRADA in ('INVOL','NI') THEN CI_OiT=&MES.;ELSE CI_OiT='';
CT_OiT=&MES.;

KEEP ID_BUNDLE ORIGEM TIPO_POSSE_RET CV_OiT CI_OiT CT_OiT;
IF ID_BUNDLE NE '';

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='' ;
END;
RUN;


DATA RET_OiT_&MESMAIS1.;
SET RET_OiT.RETIRADAS_OI_TOTAL_&MESMAIS1. (KEEP=ID_BUNDLE ORIGEM TP_RETIRADA TIPO_POSSE_RET);
     
IF TP_RETIRADA='VOL' THEN CV_OiT_MESMAIS1=&MESMAIS1.;ELSE CV_OiT_MESMAIS1='';
IF TP_RETIRADA in ('INVOL','NI') THEN CI_OiT_MESMAIS1=&MESMAIS1.;ELSE CI_OiT_MESMAIS1='';
CT_OiT_MESMAIS1=&MESMAIS1.;

KEEP ID_BUNDLE ORIGEM TIPO_POSSE_RET CV_OiT_MESMAIS1 CI_OiT_MESMAIS1 CT_OiT_MESMAIS1;
IF ID_BUNDLE NE '';

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='' ;
END;
RUN;

/*DATA RET_OiT_&MESMAIS2.;
SET RET_OiT.RETIRADAS_OI_TOTAL_&MESMAIS2. (KEEP=ID_BUNDLE ORIGEM TP_RETIRADA TIPO_POSSE_RET);
     
IF TP_RETIRADA='VOL' THEN CV_OiT_MESMAIS2=&MESMAIS2.;ELSE CV_OiT_MESMAIS2='';
IF TP_RETIRADA in ('INVOL','NI') THEN CI_OiT_MESMAIS2=&MESMAIS2.;ELSE CI_OiT_MESMAIS2='';
CT_OiT_MESMAIS2=&MESMAIS2.;

KEEP ID_BUNDLE ORIGEM TIPO_POSSE_RET CV_OiT_MESMAIS2 CI_OiT_MESMAIS2 CT_OiT_MESMAIS2;
IF ID_BUNDLE NE '';

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='' ;
END;
RUN;*/

/* Retiradas Móvel + Migdown M0 a M2 */

DATA RET_POS_&MES.;
SET RET_POS.RETIRADOS_POS_&MES. (KEEP=DDD_TELEFONE_MOVEL DS_TIPO_RETIRADA);
     
IF DS_TIPO_RETIRADA IN ('VOL','NAO IDENTIFICADO') THEN CV_POS=&MES.;ELSE CV_POS=0;
IF DS_TIPO_RETIRADA = 'INVOL' THEN CI_POS=&MES.;ELSE CI_POS=0;
CT_POS=&MES.;

KEEP DDD_TELEFONE_MOVEL CV_POS CI_POS CT_POS;

IF DDD_TELEFONE_MOVEL > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='' ;
END;
RUN;


DATA RET_POS_&MESMAIS1.;
SET RET_POS.RETIRADOS_POS_&MESMAIS1. (KEEP=DDD_TELEFONE_MOVEL DS_TIPO_RETIRADA);
     
IF DS_TIPO_RETIRADA IN ('VOL','NAO IDENTIFICADO') THEN CV_POS_MESMAIS1=&MESMAIS1.;ELSE CV_POS_MESMAIS1=0;
IF DS_TIPO_RETIRADA = 'INVOL' THEN CI_POS_MESMAIS1=&MESMAIS1.;ELSE CI_POS_MESMAIS1=0;
CT_POS_MESMAIS1=&MESMAIS1.;

KEEP DDD_TELEFONE_MOVEL CV_POS_MESMAIS1 CI_POS_MESMAIS1 CT_POS_MESMAIS1;

IF DDD_TELEFONE_MOVEL > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='' ;
END;
RUN;


/*DATA RET_POS_&MESMAIS2.;
SET RET_POS.RETIRADOS_POS_&MESMAIS2. (KEEP=DDD_TELEFONE_MOVEL DS_TIPO_RETIRADA);
     
IF DS_TIPO_RETIRADA IN ('VOL','NAO IDENTIFICADO') THEN CV_POS_MESMAIS2=&MESMAIS2.;ELSE CV_POS_MESMAIS2=0;
IF DS_TIPO_RETIRADA = 'INVOL' THEN CI_POS_MESMAIS2=&MESMAIS2.;ELSE CI_POS_MESMAIS2=0;
CT_POS_MESMAIS2=&MESMAIS2.;

KEEP DDD_TELEFONE_MOVEL CV_POS_MESMAIS2 CI_POS_MESMAIS2 CT_POS_MESMAIS2;

IF DDD_TELEFONE_MOVEL > 0;

ARRAY X(*) _NUMERIC_;
DO i = 2 TO DIM(X);
IF X(i) IN (0,.) THEN X(i)='' ;
END;
RUN;
*/
/***************************************************************************************************************/
/* Qualidade Reparo, Contestação e ASSIA ***********************************************************************/
/***************************************************************************************************************/

/* Assia Qualidade conexão banda larga */

/*DATA ASSIA_&MESMENOS1.;
SET ASSIA.ASSIA_&MESMENOS1.(KEEP=DDD_TELEFONE VELOC_CONTRATADA STATUS_ESTABILIDADE VELOC_DISP_ASSIA);
ANOMES = &MESMENOS1.;
RUN;

PROC SORT DATA= ASSIA_&MESMENOS1. NODUPKEY;BY DDD_TELEFONE;RUN;*/

/* Reparo Fixo e Banda Larga 4M */

DATA REPARO_FX_ULT4M_&MES.;
SET  REPCONS.REPARO_FX_ULT_4M_&MES. (KEEP= DDD_TELEFONE IND_TEMPO_REPARO_FX QTD_REPARO_FX_ULT_4M);
IF DDD_TELEFONE > 0;
RUN;
PROC SORT DATA= REPARO_FX_ULT4M_&MES.;BY DDD_TELEFONE;RUN;

DATA REPARO_VX_ULT4M_&MES.;
SET  REPCONS.REPARO_VX_ULT_4M_&MES. (KEEP= DDD_TELEFONE IND_TEMPO_REPARO_VX QTD_REPARO_VX_ULT_4M);
IF DDD_TELEFONE > 0;
RUN;
PROC SORT DATA= REPARO_VX_ULT4M_&MES.;BY DDD_TELEFONE;RUN;


/* Contestação */

DATA CONTESTACAO_ULT4M_&MES.;
SET  CONTCONS.CONTEST_ULT_4M_&MES. (KEEP= DDD_TELEFONE QTD_CONTESTACOES_ULT_4M);
IF DDD_TELEFONE > 0;
IND_CONTESTACAO=1;
RUN;

PROC SORT DATA= CONTESTACAO_ULT4M_&MES.;BY DDD_TELEFONE;RUN;


%MEND ORC;
/*   (MESMENOS2,MESMENOS1,MES,MESMAIS1,MESMAIS2,MESMAIS3);
%ORC (201611,201612,201701,201702,201703,201704);
%ORC (201612,201701,201702,201703,201704,201705);
%ORC (201701,201702,201703,201704,201705,201706);
%ORC (201702,201703,201704,201705,201706,201707);
%ORC (201703,201704,201705,201706,201707,201708);
%ORC (201704,201705,201706,201707,201708,201708);*/
%ORC (201705,201706,201707,201708,201708,201708);
%ORC (201706,201707,201708,201708,201708,201708);

/***************************************************************************************************************/
/* Cruzamentos *************************************************************************************************/
/***************************************************************************************************************/
%MACRO ORC (MESMENOS2,MESMENOS1,MES,MESMAIS1,MESMAIS2,MESMAIS3);
PROC SQL; 
CREATE TABLE MODELO_ANALITICO_ORC_&MES. AS
SELECT
A.ANOMES_PLANTA,
A.REGIAO,
A.UF,
A.MUNICIPIO,
A.ESTACAO,
A.DDD_TELEFONE,
A.POSSE_GERENCIAL_RESIDENCIAL,
A.POSSE_GERENCIAL_COMPLETA,
A.POSSE_RESIDENCIAL_MESMAIS1,
A.POSSE_RESIDENCIAL_II_MESMAIS1,
A.POSSE_OCT,
A.POSSE_VOZ_TOTAL,
A.AGING_FX,
A.AGING_BL,
A.AGING_TV,
A.ZONA_CIDADE,
A.CONTRATO_TV,
A.DESC_FORMA_PAGTO_TV,
A.PONTO_ADICIONAL_TV,
AI.PLANO_TV_AGRUPADO,
A.MIX_PCT_ATUAL_TV,
A.TIPO_TV,
A.ID_BUNDLE,
A.AGING_OIT,
A.TIPO_POSSE_ATUAL_MESMENOS2,	
A.TIPO_EVENTO_VENDA_MESMENOS2,
A.TP_POSSE_ATUAL,
A.TIPO_EVENTO_VENDA,
A.TIPO_POSSE_ATUAL_MESMAIS1,	
A.TIPO_EVENTO_VENDA_MESMAIS1,
G.IND_RETENCAO_MESMENOS1,
F.IND_RETENCAO_MES,
I.IND_RETENCAO_TV_MESMENOS1,
H.IND_RETENCAO_TV_MES,
AH.IND_RETENCAO_OIT_MESMENOS1,
AG.IND_RETENCAO_OIT_MES,
AF.IND_BLINDAGEM,
J.IND_RACO,
K.IND_SOLIC_PORT,
L.CV_FX,
L.CI_FX,
L.CT_FX,
M.CV_FX_MESMAIS1,
M.CI_FX_MESMAIS1,
M.CT_FX_MESMAIS1,
/*N.CV_FX_MESMAIS2,
N.CI_FX_MESMAIS2,
N.CT_FX_MESMAIS2,*/
O.CV_BL,
O.CI_BL,
O.CT_BL,
P.CV_BL_MESMAIS1,
P.CI_BL_MESMAIS1,
P.CT_BL_MESMAIS1,
/*Q.CV_BL_MESMAIS2,
Q.CI_BL_MESMAIS2,
Q.CT_BL_MESMAIS2,*/
R.CV_TV,
R.CI_TV,
R.CT_TV,
S.CV_TV_MESMAIS1,
S.CI_TV_MESMAIS1,
S.CT_TV_MESMAIS1,
/*T.CV_TV_MESMAIS2,
T.CI_TV_MESMAIS2,
T.CT_TV_MESMAIS2,*/
U.CV_OiT,
U.CI_OiT,
U.CT_OiT,
V.CV_OiT_MESMAIS1, 
V.CI_OiT_MESMAIS1,
V.CT_OiT_MESMAIS1,
/*X.CV_OiT_MESMAIS2,
X.CI_OiT_MESMAIS2,
X.CT_OiT_MESMAIS2,*/
Z.CV_POS,
Z.CI_POS,
Z.CT_POS,
AA.CV_POS_MESMAIS1,
AA.CI_POS_MESMAIS1,
AA.CT_POS_MESMAIS1,
/*AB.CV_POS_MESMAIS2,
AB.CI_POS_MESMAIS2,
AB.CT_POS_MESMAIS2,*/
AC.IND_TEMPO_REPARO_FX,
AD.IND_TEMPO_REPARO_VX,
AE.IND_CONTESTACAO
FROM STEP_01_PLANTA_&MESMENOS1. A /*LEFT JOIN STEP_01_POSSE_POSTERIOR_&MESMAIS1. 		B 	ON A.DDD_TELEFONE = B.DDD_TELEFONE
								  LEFT JOIN STEP_01_PLANTA_OIT_&MESMENOS2.			C 	ON A.DDD_TELEFONE = C.DDD_TELEFONE
								  LEFT JOIN STEP_01_PLANTA_OIT_&MESMENOS1.			D 	ON A.DDD_TELEFONE = D.DDD_TELEFONE
								  LEFT JOIN STEP_01_PLANTA_OIT_&MESMAIS1.			E 	ON A.DDD_TELEFONE = E.DDD_TELEFONE*/
								  LEFT JOIN CHAMADAS_RETENCAO_&MES.					F 	ON A.DDD_TELEFONE = F.DDD_TELEFONE
								  LEFT JOIN CHAMADAS_RETENCAO_&MESMENOS1.			G 	ON A.DDD_TELEFONE = G.DDD_TELEFONE
								  LEFT JOIN CHAMADAS_RETENCAO_TV_FULL_&MES.			H 	ON A.CONTRATO_TV = H.NUM_CONTRATO_TV
								  LEFT JOIN CHAMADAS_RETENCAO_TV_FULL_&MESMENOS1.	I 	ON A.CONTRATO_TV = I.NUM_CONTRATO_TV
								  LEFT JOIN RACO_2M_&MES.							J 	ON A.DDD_TELEFONE = J.DDD_TELEFONE
								  LEFT JOIN PORTABILIDADE_2M_&MES.					K 	ON A.DDD_TELEFONE = K.DDD_TELEFONE
								  LEFT JOIN RET_FX_&MES.							L 	ON A.DDD_TELEFONE = L.DDD_TELEFONE
								  LEFT JOIN RET_FX_&MESMAIS1.						M 	ON A.DDD_TELEFONE = M.DDD_TELEFONE
								 /* LEFT JOIN RET_FX_&MESMAIS2.						N 	ON A.DDD_TELEFONE = N.DDD_TELEFONE*/
								  LEFT JOIN RET_BL_&MES.							O 	ON A.DDD_TELEFONE = O.DDD_TELEFONE
								  LEFT JOIN RET_BL_&MESMAIS1.						P 	ON A.DDD_TELEFONE = P.DDD_TELEFONE
								  /*LEFT JOIN RET_BL_&MESMAIS2.						Q 	ON A.DDD_TELEFONE = Q.DDD_TELEFONE*/
								  LEFT JOIN RET_MIGDOWN_TV_&MES.					R 	ON A.CONTRATO_TV = R.CONTRATO
								  LEFT JOIN RET_MIGDOWN_TV_&MESMAIS1.				S 	ON A.CONTRATO_TV = S.CONTRATO
								  /*LEFT JOIN RET_MIGDOWN_TV_&MESMAIS2.				T 	ON A.CONTRATO_TV = T.CONTRATO*/
								  LEFT JOIN RET_OiT_&MES.							U 	ON A.ID_BUNDLE = U.ID_BUNDLE
								  LEFT JOIN RET_OiT_&MESMAIS1.						V 	ON A.ID_BUNDLE = V.ID_BUNDLE
								  /*LEFT JOIN RET_OiT_&MESMAIS2.						X 	ON A.ID_BUNDLE = X.ID_BUNDLE*/
								  LEFT JOIN RET_POS_&MES.							Z 	ON A.DDD_MOVEL_TITULAR = Z.DDD_TELEFONE_MOVEL
								  LEFT JOIN RET_POS_&MESMAIS1.						AA	ON A.DDD_MOVEL_TITULAR = AA.DDD_TELEFONE_MOVEL
								  /*LEFT JOIN RET_POS_&MESMAIS2.						AB 	ON A.DDD_MOVEL_TITULAR = AB.DDD_TELEFONE_MOVEL*/					
								  LEFT JOIN REPARO_FX_ULT4M_&MES.					AC 	ON A.DDD_TELEFONE = AC.DDD_TELEFONE
								  LEFT JOIN REPARO_VX_ULT4M_&MES.					AD 	ON A.DDD_TELEFONE = AD.DDD_TELEFONE
								  LEFT JOIN CONTESTACAO_ULT4M_&MES.					AE 	ON A.DDD_TELEFONE = AE.DDD_TELEFONE
								  LEFT JOIN BLIND_&MESMENOS1. 						AF  ON A.DDD_TELEFONE = AF.DDD_TELEFONE
								  LEFT JOIN CHAMADAS_OITotal_&MES.					AG  ON A.ID_BUNDLE = AG.ID_BUNDLE
								  LEFT JOIN CHAMADAS_OITotal_&MESMENOS1.			AH  ON A.ID_BUNDLE = AH.ID_BUNDLE
								  LEFT JOIN DE_PARAS.DE_PARA_PLANO_TV 				AI  ON A.PLANO_TV = AI.PLANO_TV;
QUIT;
RUN;

%MEND ORC;
/*   (MESMENOS2,MESMENOS1,MES,MESMAIS1,MESMAIS2,MESMAIS3);
%ORC (201611,201612,201701,201702,201703,201704);
%ORC (201612,201701,201702,201703,201704,201705);
%ORC (201701,201702,201703,201704,201705,201706);
%ORC (201702,201703,201704,201705,201706,201707);
%ORC (201703,201704,201705,201706,201707,201708);
%ORC (201704,201705,201706,201707,201708,201708);*/
%ORC (201705,201706,201707,201708,201708,201708);
%ORC (201706,201707,201708,201708,201708,201708);

/***************************************************************************************************************/
/* Gera relatório sumarizado e salva no diretório "OUTPUTS"  ***************************************************/
/***************************************************************************************************************/
%MACRO ORC (MESMENOS2,MESMENOS1,MES,MESMAIS1,MESMAIS2,MESMAIS3);
PROC SQL; 
CREATE TABLE MODELO_ANALITICO_ORC_AGG_&MES. AS
SELECT
ANOMES_PLANTA,
POSSE_GERENCIAL_RESIDENCIAL,
POSSE_GERENCIAL_COMPLETA,
POSSE_RESIDENCIAL_MESMAIS1,
POSSE_RESIDENCIAL_II_MESMAIS1,
POSSE_OCT,
POSSE_VOZ_TOTAL,
AGING_FX,
AGING_BL,
AGING_TV,
ZONA_CIDADE,
DESC_FORMA_PAGTO_TV,
PLANO_TV_AGRUPADO,
TIPO_TV,
AGING_OIT,
TIPO_POSSE_ATUAL_MESMENOS2,	
TIPO_EVENTO_VENDA_MESMENOS2,
TP_POSSE_ATUAL,
TIPO_EVENTO_VENDA,
TIPO_POSSE_ATUAL_MESMAIS1,	
TIPO_EVENTO_VENDA_MESMAIS1,
IND_RETENCAO_MESMENOS1,
IND_RETENCAO_MES,
IND_RETENCAO_TV_MESMENOS1,
IND_RETENCAO_TV_MES,
IND_RETENCAO_OIT_MESMENOS1,
IND_RETENCAO_OIT_MES,
IND_BLINDAGEM,
IND_RACO,
IND_SOLIC_PORT,
CV_FX,
CI_FX,
CT_FX,
CV_FX_MESMAIS1,
CI_FX_MESMAIS1,
CT_FX_MESMAIS1,
CV_BL,
CI_BL,
CT_BL,
CV_BL_MESMAIS1,
CI_BL_MESMAIS1,
CT_BL_MESMAIS1,
CV_TV,
CI_TV,
CT_TV,
CV_TV_MESMAIS1,
CI_TV_MESMAIS1,
CT_TV_MESMAIS1,
CV_OiT,
CI_OiT,
CT_OiT,
CV_OiT_MESMAIS1, 
CI_OiT_MESMAIS1,
CT_OiT_MESMAIS1,
CV_POS,
CI_POS,
CT_POS,
CV_POS_MESMAIS1,
CI_POS_MESMAIS1,
CT_POS_MESMAIS1,
IND_TEMPO_REPARO_FX,
IND_TEMPO_REPARO_VX,
IND_CONTESTACAO,
COUNT (ANOMES_PLANTA) as QTD
FROM MODELO_ANALITICO_ORC_&MES. 
GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63/*,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78*/;
QUIT;
RUN;


PROC EXPORT 
      DATA = MODELO_ANALITICO_ORC_AGG_&MES.
    OUTFILE= "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/ORCAMENTO/OUTPUTS/MODELO_ORC_ANALITICO_AGG_&MES..txt" 
    DBMS = TAB REPLACE;
RUN;


%MEND ORC;
/*   (MESMENOS2,MESMENOS1,MES,MESMAIS1,MESMAIS2,MESMAIS3);
%ORC (201611,201612,201701,201702,201703,201704);
%ORC (201612,201701,201702,201703,201704,201705);
%ORC (201701,201702,201703,201704,201705,201706);
%ORC (201702,201703,201704,201705,201706,201707);
%ORC (201703,201704,201705,201706,201707,201708);
%ORC (201704,201705,201706,201707,201708,201708);*/
%ORC (201705,201706,201707,201708,201708,201708);


/*CV_FX_MESMAIS2,
CI_FX_MESMAIS2,
CT_FX_MESMAIS2,*/
/*CV_BL_MESMAIS2,
CI_BL_MESMAIS2,
CT_BL_MESMAIS2,*/
/*CV_OiT_MESMAIS2,
CI_OiT_MESMAIS2,
CT_OiT_MESMAIS2,*/
/*CV_POS_MESMAIS2,
CI_POS_MESMAIS2,
CT_POS_MESMAIS2,*/
/*CV_TV_MESMAIS2,
CI_TV_MESMAIS2,
CT_TV_MESMAIS2,*/