DATA MIGRACAO_MAI;
SET BI_ADHOC.VW_BOV_REL_REG_DW_MULTI_MIG;
IF ANOMES_MIGRACAO IN ("201905");
KEEP DDD_FIXO MA_FIXO ID_OPR_BOV DT_MIGRACAO ANOMES_MIGRACAO TP_POSSE_ANTERIOR TP_POSSE_ATUAL;
RUN;

DATA RETIRADAS_MAI;
SET BI_ADHOC.VW_BOV_REL_REG_DW_MULTI_RET;
IF ANOMES_RETIRADA IN ("201905");
KEEP DDD_FIXO MA_FIXO ID_OPR_BOV DT_RETIRADA ANOMES_RETIRADA TP_POSSE_ANTERIOR TP_POSSE_ATUAL;
RUN;

