OPTIONS COMPRESS = YES 
          REUSE = YES
          OBS = MAX;

Libname PLNTA '/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/PLNT/TV';
Libname RET '/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RETIRADAS/TV';


%MACRO ANOMES (MESANT2,MESREF);

PROC SQL;

CREATE TABLE RET_TV_ENR_&MESREF. AS
SELECT T1.*, T2.IND_COMBO_TV
FROM RET.RET_TV_&MESREF. T1 LEFT JOIN PLNTA.PLANTA_TV_&MESANT2. T2 ON (INPUT(T1.CONTRATO_TV,8.) = T2.CONTRATO_TV);
QUIT;

DATA RET_TV_&MESREF.;
SET WORK.RET_TV_ENR_&MESREF. (KEEP=ANOMES_RETIRADA DATA_RETIRADA_TV CONTRATO_TV DESC_FORMA_PAGTO_TV TIPO_PRODUTO_TV IND_COMBO INDICADOR TIPO_RETIRADA ALONE_OIT_FINAL IND_COMBO_TV);

DIA_SEMANA = WEEKDAY(DATA_RETIRADA_TV);
SEMANA_MES = (WEEK(DATA_RETIRADA_TV,'U')+1) - WEEK(MDY(MONTH(DATA_RETIRADA_TV),1,YEAR(DATA_RETIRADA_TV)),'U');

IF TIPO_PRODUTO_TV = 'TV ANTENEIROS POS-PAGO' THEN TIPO_PRODUTO = 'ANTENEIRO';ELSE TIPO_PRODUTO = 'COMODATO';

IF IND_COMBO_TV = 'MULTI' THEN IND_COMBO_TV_INICIAL = 'MULTI';
ELSE IF TIPO_PRODUTO_TV = 'TV ANTENEIROS POS-PAGO' THEN IND_COMBO_TV_INICIAL = 'ALONE';
ELSE IND_COMBO_TV_INICIAL = 'ALONE';

IF ALONE_OIT_FINAL = 'OI Total' THEN IND_COMBO_TV_FINAL = 'MULTI';
IF TIPO_PRODUTO_TV = 'TV ANTENEIROS POS-PAGO' THEN IND_COMBO_TV_FINAL = 'ALONE';
ELSE IND_COMBO_TV_FINAL = 'ALONE';

RUN;

%MEND ANOMES;
/*%ANOMES (201712,201801);
%ANOMES (201801,201802);
%ANOMES (201802,201803);
%ANOMES (201802,201804);
%ANOMES (201803,201805);
%ANOMES (201804,201806);
%ANOMES (201805,201807);
%ANOMES (201806,201808);
%ANOMES (201807,201809);
%ANOMES (201808,201810);
%ANOMES (201809,201811);
%ANOMES (201810,201812);
%ANOMES (201811,201901);
%ANOMES (201902,201904);*/
%ANOMES (201903,201905);
%ANOMES (201904,201906);
%ANOMES (201905,201907);
%ANOMES (201906,201908);

%MACRO REF(M1,M2,M3,M4);

DATA CONSOLIDA_RET_TV_2019;

SET	WORK.RET_TV_&M1.
	WORK.RET_TV_&M2.
	WORK.RET_TV_&M3.
	WORK.RET_TV_&M4.;
/*	WORK.RET_TV_&M5.
	WORK.RET_TV_&M6.
	WORK.RET_TV_&M7.
	WORK.RET_TV_&M8.
	WORK.RET_TV_&M9.
	WORK.RET_TV_&M10. */
RUN;

%MEND REF;
%REF (201905,201906,201907,201908);

/*PROC SQL;

CREATE TABLE COUNT_RET_TV_2018 AS

SELECT 

ANOMES_RETIRADA,
DIA_SEMANA,
SEMANA_MES,
DESC_FORMA_PAGTO_TV,
TIPO_PRODUTO,
IND_COMBO_TV_INICIAL,
IND_COMBO_TV_FINAL,
CASE
	WHEN TIPO_PRODUTO = 'ANTENEIRO' THEN 'ALONE'	
	WHEN IND_COMBO_TV_FINAL = 'ALONE' AND IND_COMBO_TV_INICIAL = 'MULTI' THEN 'MULTI' 
	ELSE IND_COMBO_TV_FINAL END AS IND_COMBO_COMPOSTO,
	
INDICADOR,
TIPO_RETIRADA,

COUNT (DISTINCT CONTRATO_TV) AS TOTAL FROM 	WORK.CONSOLIDA_RET_TV_2018

GROUP BY 

ANOMES_RETIRADA,
DIA_SEMANA,
SEMANA_MES,
DESC_FORMA_PAGTO_TV,
TIPO_PRODUTO,
IND_COMBO_TV_INICIAL,
IND_COMBO_TV_FINAL,
IND_COMBO_COMPOSTO,
INDICADOR,
TIPO_RETIRADA;

QUIT;