OPTIONS
     COMPRESS = YES
     REUSE = YES
     OBS        = MAX;

LIBNAME PLANTA   "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/PLNT/FIXO_BL_TV";
LIBNAME TV       "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/PLNT/TV";
LIBNAME RET_FX   "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RETIRADAS/FIXO";
LIBNAME RET_BL   "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RETIRADAS/VELOX";
LIBNAME RET_TV   "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RETIRADAS/TV";
LIBNAME RET_OIT  "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/RETIRADAS/OiTotal";
LIBNAME ZONA     "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/ZONA";
LIBNAME DE_PARAS "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/DE_PARAs";
LIBNAME DEPARA  "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/AD_HOC/Diogo/depara";
LIBNAME NBA      "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/NBA";
LIBNAME NBA_OiT  "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/OIT";
LIBNAME WAR      "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/WAR";
LIBNAME FAT_REC  "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/FAT_REC";
LIBNAME RET_FIB "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/Fibra/Retiradas";
LIBNAME PLT_FIB "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/Fibra/Planta";
LIBNAME AD_HOC  "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/AD_HOC/Diogo";
LIBNAME FAT_R1 "/sasdata/ger_trafego_mkt/FATURADO/R1";
LIBNAME GORI "/sasdata/ger_trafego_mkt/AQUISICAO/MARCELLO";
LIBNAME DT_MRT "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/DATA_MART";
LIBNAME UPLOAD "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/AD_HOC/FELIPE_MIGUEL/Upload";
LIBNAME RENAN  "/sasdata/ger_trafego_mkt/RETENCAO/RETENCAO/AD_HOC/RENAN";
/**/
/*%MACRO A(ANOMES,DATA1,DATA2);*/
/**/
/*PROC SQL;*/
/*CREATE TABLE VALID_GMC_&ANOMES. AS */
/*SELECT DISTINCT*/
/*"&ANOMES." AS ANOMES_PLANTA,*/
/*A.ACESSO_GPON,*/
/*A.ID_BUNDLE,*/
/*INPUT(A.DATA_INSTALACAO_GPON, YYMMDD10.) AS DATA_PLANTA FORMAT DDMMYY10.,*/
/*A.OFERTA_ATUAL AS OFERTA_PLANTA,*/
/*B.DATA_FECHAMENTO_MIG AS DATA_GMC,*/
/*B.OFERTA_DEST AS OFERTA_GMC,*/
/*CASE*/
/*	WHEN OFERTA_ATUAL = OFERTA_DEST THEN 'VERDADEIRO' ELSE 'FALSO' END AS FLG_OFERTA*/
/*FROM DT_MRT.PLANTA_FIBRA_&ANOMES. AS A LEFT JOIN DT_MRT.GMC_MIGRACAO_FIBRA_&ANOMES. AS B ON A.ID_BUNDLE = B.ID_BUNDLE AND A.CPF_CNPJ = B.CPF_CNPJ;*/
/*QUIT;*/
/**/
/*DATA VALID_GMC_VIEW;*/
/*SET VALID_GMC_&ANOMES.;*/
/**/
/*WHERE DATA_GMC > DATA_PLANTA;*/
/**/
/*RUN;*/
/**/
/*%MEND A;*/
/*%A(202112);*/

PROC SQL;
CREATE TABLE CHECK_OFERTA AS 
SELECT
INPUT(DDD_FIXO,20.) AS DDD_FIXO,
INPUT(NUMERO_FIXO,20.) AS NUMERO_FIXO,
ID_BUNDLE,
NUMERO_DOCUMENTO,
CTA_FATURA_BUNDLE,
OFT_MOVEL_ATUAL,
OFERTA_ATUAL,
CASE
	WHEN OFERTA_ATUAL = OFT_MOVEL_ATUAL THEN 'VERDADEIRO' ELSE 'FALSO' END AS FLG_OFERTA
FROM DT_MRT.PLANTA_FIBRA_TRAT_202112
WHERE OFERTA_ATUAL IS NOT NULL AND OFT_MOVEL_ATUAL IS NOT NULL AND IND_COMBO = 'MULTI'
HAVING FLG_OFERTA = 'FALSO'
;QUIT;

PROC SQL;
CREATE TABLE CHECK_GMC_TOTAL AS 
SELECT
A.*,
B.DDD_FIXO,
B.NUMERO_FIXO
FROM DT_MRT.GMC_MIGRACAO_FIBRA_TOTAL AS A INNER JOIN CHECK_OFERTA AS B ON A.ID_BUNDLE = B.ID_BUNDLE AND A.CPF_CNPJ = INPUT(B.NUMERO_DOCUMENTO,14.);
QUIT;

PROC SQL;
CREATE TABLE CHECK_GMC_TOTAL_TEL AS 
SELECT DISTINCT
B.*
FROM DT_MRT.GMC_MIGRACAO_FIBRA_TOTAL AS B INNER JOIN CHECK_GMC_TOTAL AS A ON A.DDD_FIXO = B.NO_DDD AND A.NUMERO_FIXO = B.NO_TELEFONE;
QUIT;

PROC SQL OUTOBS=1;
CREATE TABLE CAMPOS_GMC AS 
SELECT
*
FROM BI_ADHOC.VW_DW_GMC_DET_MIGRACAO_OS;
QUIT;
